### ISSUE TITLE
Expose project as an output.

### ISSUE THREAD

**Issue by tmc** [forseti-security/terraform-google-forseti#101]

**Comment by agold-rh** [comment]
I'll take a look at this one.

**Comment by kevensen** [comment]
@tmc @agold-rh For documentation purposes, is there a use case?  If so, could you please note that here?

**Comment by gkowalski-google** [comment]
@tmc @agold-rh Following up, can you provide more details on the use case?

**Comment by gkowalski-google** [comment]
Closing this out, please re-open if you have a valid use case. Today the project ID is passed to the Forseti module as an input.
