### ISSUE TITLE
Add Slack config for all resource notifiers

### ISSUE THREAD

**Issue by julianvmodesto** [forseti-security/terraform-google-forseti#130]
Currently, only specific notifiers like IAM and KMS have Slack as a configuration option for notifications.

**Comment by bmenasha** [comment]
There are 480 variables in this module.   

I don't see the point of adding more.  Why can't we just accept that the yaml file is part of the install process and needs to be supplied in the install and it's best to direct the user to modify the server config yaml like any other config file rather then this template expansion we currently do?
thanks

**Comment by morgante** [comment]
@bmenasha We specifically use this because the upgrade story between Forseti versions was historically painful, with requiring manual tweaks to the config file format. The templating is an attempt to work around that by generating the config value from known inputs.

**Comment by bmenasha** [comment]
thanks @morgante that makes sense.  I added a new variable  `violations_slack_webhook` which will configure the slack notification webhook for all notifiers with this PR https://github.com/forseti-security/terraform-google-forseti/pull/160#partial-pull-merging
thanks

**Comment by gkowalski-google** [comment]
This has been completed.
