### ISSUE TITLE
org_id should be optional

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#140]
When passing `folder_id` without `org_id`, we should be able to create a Forseti that:

* Scans only the folder identified by `folder_id` (already done with `root_resource_id`)
* Only grants permissions on the folder level

Currently, when passing both flags, **all** the organization-level roles are still granted (most are not needed since Forseti will be bound to a folder). This can be a blocker for companies where separation of business units at the top-level is important.

I'm wondering if Forseti can work without any organization permissions, but it should be (at minimum the service accounts should have limited org-level roles if `folder_id` is passed).

**Comment by umairidris** [comment]
As a follow up to the request, I would like the module to also have the option to just install Forseti in the host project (and let the user manually grant access to other resources as needed).
