### ISSUE TITLE
Remove Organization Admin as a requirement

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#141]
`Organization Administrator` is a role that can potentially be very destructive.

We need to identify a subset of permissions that are really needed to create Forseti, and possibly help create a custom role that might have **only** those permissions (in case users are not comfortable with granting the wider role).

So far, we've identified that the `Organization Administrator` role can be replaced with a custom role with the following permissions:
* resourcemanager.projects.getIamPolicy
* resourcemanager.organizations.getIamPolicy
* resourcemanager.organizations.setIamPolicy
* resourcemanager.folders.getIamPolicy
* resourcemanager.folders.setIamPolicy

**Comment by securitygeneration** [comment]
I have to add my vote to @ocervell's on this point. This is a role that I normally wouldn't grant at all, and any organisation that follows the principle of least privilege (as we all should) would want to only grant Forseti the absolute minimum it needs.

I understand the role of the `Enforcer` module (and even that shouldn't need all permission), but as a primarily audit-focused solution, couldn't Forseti run in a read-only mode with far fewer permissions?

**Comment by morgante** [comment]
@securitygeneration I think there might be a bit of confusion here.

Forseti itself does **not** need the Org Admin role to function. The (read-only) roles that Forseti needs are documented [here](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/main.tf#L64).

Org Admin is only required for the user or Service Account installing Forseti (primarily so that they're able to grant Forseti the access it needs).

**Comment by securitygeneration** [comment]
@morgante Ah yes, that does make sense, thankfully 😊  But then it strikes me that you don't necessarily need to have Org Admin to set those perms, but rather just have the ability to provide them to the service account, which could be achieved with a Custom Role.

**Comment by morgante** [comment]
@securitygeneration We don't actually require that you have Org Admin. So long as you have the needed permissions, install should work.

**Comment by paskal** [comment]
I have issue which is related to that: I'm not willing to grant `Organization Administrator` to someone, and I'm not willing to deploy Forseti Terraform module using forseti-server service account. I think there should be separate set of permissions required just for deployment.
If it would be easier for your team to track it as a separate issue, let me know and I will create it.

**Comment by dekuhn** [comment]
@kevensen Correct me if I am wrong either we have a deployment service account or that is in the works which would address @paskal concerns?

**Comment by kevensen** [comment]
@paskal Re-iterating morgante's comments, the forseti-server service account doesn't need Organization Admin.  Nominally, the deployer service account does.

**Comment by paskal** [comment]
Thank you @kevensen! My position stands still: I would like to have an account with a separate set of permissions for just deployment, and a separate one for running forseti-server.

Now they are merged together in the documentation and it's up to a user to figure out how to separate them.

Also, it would be nice to explain in documentation why OrgAdmin is necessary and what should you do if you don't want to grant this permission (I believe, create service accounts for client and server manually is the answer to that).

**Comment by kevensen** [comment]
@paskal Understood.  The [helpers/setup.sh](https://github.com/forseti-security/terraform-google-forseti/blob/master/helpers/setup.sh) creates a service account just for deploying Forseti via Terraform.  Then, the Terraform module will create the server and client service accounts.

I'd be happy to help you with the execution script.

**Comment by kevensen** [comment]
The documentation refers to this as the [Cloud Foundation Service Account](https://forsetisecurity.org/docs/latest/concepts/service-accounts.html#the-cloud-foundation-service-account).  The title of this could be more clear.

**Comment by paskal** [comment]
> The documentation refers to this as the [Cloud Foundation Service Account](https://forsetisecurity.org/docs/latest/concepts/service-accounts.html#the-cloud-foundation-service-account). The title of this could be more clear.

Excellent, that's exactly what I was looking for. I think clarifying the title and the fact that this account will be used only for terraform\cloud foundation deploy and not for the Forseti server itself would make the situation absolutely clear.

**Comment by kevensen** [comment]
Thanks for the feedback.  I'll take care of this today.

**Comment by dekuhn** [comment]
This doc (https://forsetisecurity.org/docs/latest/concepts/service-accounts.html#the-cloud-foundation-service-account) needs to be updated and point to the Forseti installation process where this service account is needed temporarily to bootstrap the install Forseti. The Forseti installation has details on creating this service account and a script to deprovision the service account once Forseti is installed.

@kevensen Did you update the docs related to this or is this still pending?
