### ISSUE TITLE
CSCC API + Role Enablement

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#142]
If `cscc_violations_enabled` is set to `"true"`, then maybe we should:

* Enable the Cloud Command Security Center API (`securitycenter.googleapis.com`) in the Forseti project
* Grant the `roles/securityCenter.editor` role to the Forseti server service account

Those are two manual steps that are still required when setting up the integration.

**Comment by angstwad** [comment]
I got it

**Comment by angstwad** [comment]
Should grant `roles/securitycenter.findingsEditor` to server service acct

**Comment by morgante** [comment]
@angstwad I believe the role part also needs to be added.

**Comment by angstwad** [comment]
@morgante it was added in https://github.com/forseti-security/terraform-google-forseti/commit/a3af880fe489f763af36d9a73420fa4a3c343788
