### ISSUE TITLE
Input Parameter cloudsql_db_name not respected in cloudsql

### ISSUE THREAD

**Issue by BobcatProgrammer** [forseti-security/terraform-google-forseti#146]
Hi guys,

I used the input variable 
`cloudsql_db_name  = "my-custom-db-name"`
to change the db name that gets used. This gets configured correctly in the settings and startup script for the server, especially here:
https://github.com/forseti-security/terraform-google-forseti/blob/065c03c6d9e8aaf3142e29bf02ace11e8cbc978d/modules/server/templates/scripts/forseti-server/forseti_env.sh.tpl#L3

But it is not respected for the definition of the cloudsql db here:
https://github.com/forseti-security/terraform-google-forseti/blob/065c03c6d9e8aaf3142e29bf02ace11e8cbc978d/modules/server/main.tf#L465

This led to an non working setup after running the module. I would suggest to fix that, if you want I can do a PR.

Regards,
Simon

**Comment by morgante** [comment]
Good catch, yes a PR would be appreciated. Thanks!

**Comment by gkowalski-google** [comment]
This issue was resolved with https://github.com/forseti-security/terraform-google-forseti/pull/151.
