### ISSUE TITLE
Changing rule config should not destroy/recreate server VM

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#147]
`depends_on` on `module.server_rules` for the server VM means everytime a user changes a rule file (frequent when starting with Forseti), the whole VM gets re-created.

There is no need for this: ideally what should happen is that we run `gsutil cp -R <BUCKET>/rules <FORSETI_HOME>/rules` and then `forseti server configuration reload`. Simplier, we can just restart the server VM so that the startup script is re-executed when changing configs.

**Comment by umairidris** [comment]
Note that provisioners (like local-exec etc) are often banned for security reasons, so shouldn't be required.
