### ISSUE TITLE
Terraform destroy fails on google_sql_user

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#148]
I ran into an error while running `tf destroy` on a simple Forseti deployment:

```
Error: Error applying plan:

1 error(s) occurred:

* module.forseti-install-simple.module.server.google_sql_user.root (destroy): 1 error(s) occurred:

* google_sql_user.root: Error, failed to deleteuser root in instance forseti-server-db-ce89442d: googleapi: Error 400: Missing parameter: host., required
```

Another `tf destroy` afterwards also gave me some weird errors:

```
11 error(s) occurred:

* module.forseti-install-simple.module.server.output.forseti-server-storage-bucket: variable "server_config" is nil, but no error was reported
* module.forseti-install-simple.module.client.output.forseti-client-vm-public-ip: Resource 'google_compute_instance.forseti-client' does not have attribute 'network_interface.0
.access_config.0.nat_ip' for variable 'google_compute_instance.forseti-client.network_interface.0.access_config.0.nat_ip'
* module.forseti-install-simple.local.random_hash: local.random_hash: variable "random_hash_suffix" is nil, but no error was reported
* module.forseti-install-simple.module.server.output.forseti-server-vm-ip: variable "forseti-server" is nil, but no error was reported
* module.forseti-install-simple.module.client.output.forseti-client-storage-bucket: Resource 'google_storage_bucket.client_config' does not have attribute 'id' for variable 'go
ogle_storage_bucket.client_config.id'
* module.forseti-install-simple.module.server.output.forseti-server-service-account: variable "forseti_server" is nil, but no error was reported

* module.forseti-install-simple.module.client.output.forseti-client-vm-name: Resource 'google_compute_instance.forseti-client' does not have attribute 'name' for variable 'goog
le_compute_instance.forseti-client.name'
* module.forseti-install-simple.module.server.output.forseti-server-vm-name: variable "forseti-server" is nil, but no error was reported
* module.forseti-install-simple.module.server.output.forseti-server-vm-public-ip: variable "forseti-server" is nil, but no error was reported
* module.forseti-install-simple.module.client.output.forseti-client-service-account: Resource 'google_service_account.forseti_client' does not have attribute 'email' for variab
le 'google_service_account.forseti_client.email'
* module.forseti-install-simple.module.client.output.forseti-client-vm-ip: Resource 'google_compute_instance.forseti-client' does not have attribute 'network_interface.0.networ
k_ip' for variable 'google_compute_instance.forseti-client.network_interface.0.network_ip'
```

**Comment by aaron-lane** [comment]
This seems to be an issue with the provider as the [host parameter is optional](https://www.terraform.io/docs/providers/google/r/sql_user.html#host) and this error only occurs on destroy. From what I've gleaned in the CI logs, this only occurs when the `google_sql_database` is destroyed before the `google_sql_user`, though I have been unsuccessful in enforcing an explicit dependency from the user to the database. #159 works around this by ignoring errors during `kitchen destroy` in the CI pipeline, but a real fix is needed. Setting the host parameter to the private IP address of the `google_sql_database_instance` could work, but we need https://github.com/forseti-security/forseti-security/pull/2834 or https://github.com/forseti-security/forseti-security/pull/2715 to be shipped first.

**Comment by kevensen** [comment]
Just FYI, I am seeing this too in v3.0.0.  I'd be happy to implement a fix with a little guidance.

**Comment by morgante** [comment]
This might be a provider issue.

**Comment by kevensen** [comment]
After investigation, I think it is a provider issue.  If I understand correctly, it has to do with the REST API actually requiring the *host* URL parameter when deleting a user.

https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users/delete

**Comment by kevensen** [comment]
On insert, the parameter is optional.

https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users/insert

**Comment by kevensen** [comment]
Closing based on merged PR.  Please re-open if issue reappears.

**Comment by snoozesecurity** [comment]
> 
> 
> Closing based on merged PR. Please re-open if issue reappears.

I am still experiencing this issue, just ran terraform destroy and got the following:

module.forseti.module.server.google_sql_user.root: Destroying... [id=root//forseti-server-db-string]
Error: Error, failed to deleteuser root in instance forseti-server-db-string: googleapi: Error 400: Missing parameter: host., required

**Comment by morgante** [comment]
@snoozesecurity Could you file an [upstream issue](https://github.com/terraform-providers/terraform-provider-google/issues/new/choose)? This seems to be an issue in the provider.

**Comment by morgante** [comment]
Notably, this also seems to be an issue if you update to a new module version which changes the `google_sql_user` resource.

**Comment by morgante** [comment]
Hoping for an upstream fix: https://github.com/forseti-security/terraform-google-forseti/issues/148

**Comment by gkowalski-google** [comment]
This issue has been resolved.
