### ISSUE TITLE
Document requirements of examples

### ISSUE THREAD

**Issue by aaron-lane** [forseti-security/terraform-google-forseti#150]
Similar to the README of the root module, the READMEs of the example modules should define the required permissions and APIs.

**Comment by kevensen** [comment]
It looks like the following are missing requirements:

- examples/external_ip
- examples/install_simple
- examples/real_time_enforcer
- examples/shared_vpc
- examples/simple_example

**Comment by morgante** [comment]
I think most of the examples have the same requirements as the root module so this isn't high priority.
