### ISSUE TITLE
Resources remain after `kitchen destroy` fails in pipeline

### ISSUE THREAD

**Issue by aaron-lane** [forseti-security/terraform-google-forseti#165]
#159 ignores errors during `kitchen destroy` to work around #148, but this means that some resources are not being cleaned up by the pipeline. We will need to explicitly clean those resources separately until #148 is fixed.

**Comment by kevensen** [comment]
Oddly, I "think" this is still broken.  e.g. https://concourse.infra.cft.tips/builds/4583

**Comment by morgante** [comment]
IMO we should expect `destroy` to work for unsuccessful applies.

Instead, I think we move towards ephemeral projects which we can entirely wipe after a test run.

**Comment by aaron-lane** [comment]
@morgante I agree. We should move the test project configuration in to the repository to provide a consistent approach for provisioning test projects and get rid of this mess.
