### ISSUE TITLE
Make Forseti user directory and path configurable

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#17]
We need to: 
* make the `USER=ubuntu` configurable in startup scripts.
* make Forseti's path configurable (atm. hardcoded to `/home/ubuntu/forseti-security`).
* See [#14 comment](https://github.com/terraform-google-modules/terraform-google-forseti/pull/14/files/98043cc4fa661e31c65434ea650f5fdea47dc593#r225727500)

Users should be able to choose their own user on their VM, and change the path where Forseti should be installed.

**Comment by adrienthebo** [comment]
Note that as of Forseti v2.14 it looks like the forseti home directory is hardcoded to be `/home/ubuntu`: https://github.com/GoogleCloudPlatform/forseti-security/blob/854004e960fea4d92697c5a3ee95bd069b8aef2c/install/gcp/scripts/initialize_forseti_services.sh#L43

**Comment by kevensen** [comment]
@ocervell Is this feature still desired?

**Comment by ocervell** [comment]
Yep, if we want to deploy Forseti on other OSes one day ...

**Comment by gkowalski-google** [comment]
At this time we plan to support Forseti on GCE running Ubuntu, along with Forseti running on GKE. Focusing on GKE and if in the future we decide to support other OS, then we will re-visit.
