### ISSUE TITLE
Terraform 0.12.x

### ISSUE THREAD

**Issue by RexBelli** [forseti-security/terraform-google-forseti#172]
It looks like the [new version](https://www.terraform.io/upgrade-guides/0-12.html) of Terraform made some breaking changes to the syntax.  Indeed when I tried to use this module with the new version, I quickly ran into errors I wasn't sure how to resolve.

I ran the included migration tool (I committed the results [here](https://github.com/RexBelli/terraform-google-forseti/commit/98108b67042ce92c2cf3d39be151c88218a78abf)), and am still receiving errors: 
```
Error: Incorrect condition type

  on terraform-google-forseti/modules/server/main.tf line 252, in data "template_file" "forseti_server_config":
 252:     GROUPS_SETTINGS_DISABLE_POLLING                     = var.groups_settings_disable_polling ? "true" : "false"
    |----------------
    | var.groups_settings_disable_polling is "False"

The condition expression must be of type bool.
```

Are there plans to add support for the new version?

**Comment by morgante** [comment]
Yes, we do plan to add support in the coming few weeks but it will be a gradual process.

**Comment by hshin-g** [comment]
+1 to this as Cloud Shell comes with Terraform v0.12.2.

**Comment by jeffmccune** [comment]
Gary and I are working on this

Acceptance Criteria:

 * [ ] CI passes in the aaron-lane-0.12 release branch PR.
 * [ ] README includes note about 0.12 support
 * [ ] README includes last release supporting 0.11
 * [ ] CHANGELOG staged and ready to release
 * [ ] Modules and providers pinned to appropriate versions for 0.12.
 * [ ] All changes reviewed and merged.

**Comment by jeffmccune** [comment]
Gary and I left off trying to troubleshoot this error:

```
Error: Error patching router us-central1/forseti-simple-example-midge: googleapi: Error 400: Invalid value for field 'resource.nats[0].subnetworks[0].sourceIpRangesToNat': ''. The subnetwork is already configured with ALL_IP_RANGES for Nat which conflicts with the specified IpRangeToNatOption options in this Nat., invalid

  on ../../../examples/real_time_enforcer/nat.tf line 41, in resource "google_compute_router_nat" "main":
  41: resource "google_compute_router_nat" "main" {
```

Here's the build log location.  We're sort of stumped, this may be an issue with the provider?

https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-forseti/jobs/integration-tests/builds/519#L5d1c3fba:365

**Comment by jeffmccune** [comment]
@aaron-lane @ingwarr Gary and I are picking up working on the forseti lint test job, which is failing in  ~3 ways.  Once lint tests are passing we'll work on the `sourceIpRangesToNat` issue.

**Comment by jeffmccune** [comment]
Lint tests are green as of 6d634ac `Fix make generate_docs for 0.12` in #202 

Switching back to working on the integration tests.

**Comment by jeffmccune** [comment]
@aaron-lane @ingwarr `kitchen verify simple-example-local` is passing on my local machine as of e7cc11a `Fix boolean logic error in module.server.null_resource.missing_emails for 0.12`

In CI, we're still getting the `The subnetwork is already configured with ALL_IP_RANGES` error.  See [this line](https://concourse.infra.cft.tips/teams/cft/pipelines/terraform-google-forseti/jobs/integration-tests/builds/529#L5d1c4166:341) in Build 529.

In CI, the following are passing:
 * run-tests-real-time-enforcer
 * run-tests-real-time-enforcer-roles
 * run-tests-real-time-enforcer-sinks

See the capture of the output of `kitchen verify simple-example-local` to inform the 0.12.x release.

https://gist.github.com/jeffmccune/508d3c06d145a4a723290b25257bcba5

**Comment by aaron-lane** [comment]
Great! Let's verify `shared-vpc-local` works locally and we can wrap this up.

**Comment by jeffmccune** [comment]
@aaron-lane I verified `shared-vpc-local` as of ab6afc3 `Update make docker_run for 0.12.x`, results at https://paste.googleplex.com/5801612691898368

**Comment by jeffmccune** [comment]
@aaron-lane I verified `shared-vpc-local` as of ab6afc3 `Update make docker_run for 0.12.x`, results at https://gist.github.com/jeffmccune/c2d12dca8f80c7f0eff2af06e6e96f93
