### ISSUE TITLE
Custom Rules Workflow

### ISSUE THREAD

**Issue by cleibl** [forseti-security/terraform-google-forseti#179]
How should I handle creation of custom rules?  For example, the Service Account Key rule currently is set to 100 days in the rules module, but what if I want that to be 90?  

Should I send a pull request to update this module with another variable or is there some way I can add custom rules?  Fork this repo and start my own custom module?

My ideal process would be that when a config rule changes in source, it would start a chain of events which would update that rule in the bucket and have forseti re-run the scanners.

**Comment by aaron-lane** [comment]
Hi @cleibl! What you're discussing sounds like a reasonable extension to the module. Are there additional rules which you would like to customize at this point?

**Comment by morgante** [comment]
I don't think this module can reasonably handle all rule changes/customizations unfortunately.

Instead, I think the minimum this module needs to do is ensure that it doesn't overwrite customized rules unexpectedly. Is that case?

In terms of automatically re-running Forseti scanners on rule changes, I quite agree/sympathize but think it's more of a core Forseti architecture discussion which I would delegate to @hshin-g.

**Comment by aaron-lane** [comment]
Could we provide a mechanism to allow users to override the existing rule files with their own content?

**Comment by gkowalski-google** [comment]
Update website documentation to provide a process for how users should manage rules when using Terraform.
