### ISSUE TITLE
More validation and choices for regions / zones

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#18]
cf:
* [#14 (comment)](https://github.com/terraform-google-modules/terraform-google-forseti/pull/14/files/98043cc4fa661e31c65434ea650f5fdea47dc593#r225730131)
* [#14 (comment 2)](https://github.com/terraform-google-modules/terraform-google-forseti/pull/14/files/98043cc4fa661e31c65434ea650f5fdea47dc593#r225724635)

**Comment by kevensen** [comment]
@ocervell @aaron-lane can this issue be closed?
