### ISSUE TITLE
Allow module to import existing Forseti installations

### ISSUE THREAD

**Issue by umairidris** [forseti-security/terraform-google-forseti#197]
Right now the user cannot import an existing installation using `terraform import`. This is due to the module adding random suffix to resources. It would be beneficial if the user could specify the resource names to the names of an existing installation, thus allowing for imports.

**Comment by morgante** [comment]
I'm worried about the complexity of adding separate variables for each resource name.

Could we solve this by adding a `resource_name_suffix` input variable which would be used as the suffix on resource names (default to random)?

**Comment by umairidris** [comment]
That sounds reasonable, assuming the python installer and terraform share the base resource names.
