### ISSUE TITLE
kubernetes_engine_scanner does not work

### ISSUE THREAD

**Issue by aweberlopes** [forseti-security/terraform-google-forseti#204]
Hello Together,

I used the actuall terraform module deploy forseti. 
Actually i created the SA Account with the helper scripts and deployed it with terraform version 0.11

So I tried to run the scanner on a model and both auf kubernetes engine modules give me this errors:

`}
{
  "serverMessage": "Error running scanner: KeScanner: '\''Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n    ke_clusters = self._retrieve()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n    parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'\''"
}
{
  "serverMessage": "Error running scanner: KeVersionScanner: '\''Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n    ke_clusters = self._retrieve()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n    parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'\''"
}
{`

the questions is why it is not working. I sitting around nearly 2 Days but don't understand why it fails.

Dear Reagrets 
Alex Weber Lopes

**Comment by morgante** [comment]
I don't think this is related to the Terraform installer. Please follow one of these channels for getting help with Forseti: https://forsetisecurity.org/docs/latest/use/get-help.html

**Comment by blueandgold** [comment]
I looked into this.  It's because the user's env is missing the `kubernetes_service_config` data in the db.  See screenshot below.

![image](https://user-images.githubusercontent.com/6977544/61684032-c6cadc00-accc-11e9-9bae-a965eac8745a.png)

**Comment by morgante** [comment]
@blueandgold Is it related to the Terraform module? What's the fix?

**Comment by mschlanser** [comment]
Error for me as well ( below ).  Any idea when this is going to be fixed?

{
  "serverMessage": "Error running scanner: KeVersionScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n    ke_clusters = self._retrieve()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n    parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'"
}

**Comment by kevensen** [comment]
I think this is related to an issue in forseti-security/forseti-security

https://github.com/forseti-security/forseti-security/issues/3106
