### ISSUE TITLE
Forseti Server VM's startup script fails to install Forseti

### ISSUE THREAD

**Issue by garrettwong** [forseti-security/terraform-google-forseti#206]
`forseti` does not appear to be installed on the forseti-server-vm post-deployment.  Anyone able to reproduce this?

Hitting issues with pip vs. pip3.  After addressing that, hitting issues with setuptools.  (sudo apt-get install -y python-setuptools... which "python-setuptools" would need to be placed in installer/dependencies/apt_packages.txt)

Forseti installation is based on the following TF vars.
```
module "forseti" {
  source  = "terraform-google-modules/forseti/google"
  version = "~> 2.0.0"

  gsuite_admin_email = "[email]"
  domain             = "[domain.com]"
  project_id         = "[project_id]"
  org_id             = "[org_id]"
  forseti_version    = "v2.18.0"

  network = "[shared_vpc_network]"
  network_project = "[shared_vpc_network_project_id]"
  subnetwork = "[shared_vpc_subnetwork]"

  client_region = "us-west1"
  server_region = "us-west1"
  cloudsql_region = "us-west1"
}
```

**Comment by blueandgold** [comment]
@hshin-g Can you please investigate this issue?

**Comment by garrettwong** [comment]
Per further evaluation and testing we've uncovered a few key callouts.  3.0.0 only appears to be compatible with terraform 12.x and does not work with terraform 11.x.    Have tested a few of the following configurations and they are noted below:

  |   | Terraform 11.x | Terraform 12.x
-- | -- | -- | --
  | TF Module | 2.3.0 | 3.0.0
Forseti Version |   |   |  
v2.15.0 |   | Success | TBD
v2.16.0 |   | TBD | TBD
v2.17.0 |   | TBD | Success - 7/24/19
v2.18.0 |   | Fail - 7/24/19 | Success - 7/24/19

**Comment by morgante** [comment]
Correct, this is noted in the module documentation [here](https://github.com/forseti-security/terraform-google-forseti#compatibility).
