### ISSUE TITLE
Add additional submodules to support more deployment scenarios

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#208]
It would be useful to have an option to conditionally deploy the server VM.  For example, if deploying Forseti on GKE, the server VM is an unnecessary resource.  

To keep this focused, the resolution ought to be agnostic of "Forseti on GKE".

This stems from issue #169

**Comment by morgante** [comment]
I'm not sure this is the right way to approach this. The main module is for a full Forseti install (including VMs). It primarily just calls submodules (see main.tf) which contain the individual resources.

Instead of conditionally deploying the server VM, we should make sure there are appropriate (shared) submodules which the GKE implementation can use for everything it *does* need. Does that make sense?

**Comment by kevensen** [comment]
Thanks for the feedback @morgante .  I'd like to suggest that a "full Forseti install" doesn't necessarily  include VM's if deploying on GKE.

That said, I am open to suggestions.  In this case, would we break out CloudSQL and the GCS bucket resources to submodules different from the server?

**Comment by morgante** [comment]
> Thanks for the feedback @morgante . I'd like to suggest that a "full Forseti install" doesn't necessarily include VM's if deploying on GKE.

Totally agreed. I mean that the root module is a VM-based "full Forseti install" while the GKE module can be another entrypoint for a full Forseti install (which would not include VM creation).

> That said, I am open to suggestions. In this case, would we break out CloudSQL and the GCS bucket resources to submodules different from the server?

Precisely.

**Comment by kevensen** [comment]
Gotcha.  This makes sense.  I'd like to make this fairly granular.  I think we should make a sub-module each for:

1. Server GCS bucket
2. Server IAM
3. Client GCS bucket
4. Client IAM
3. CloudSQL  instance

**Comment by morgante** [comment]
That makes sense to me.

**Comment by kevensen** [comment]
Will address by Forseti 2.22

**Comment by kevensen** [comment]
Addressed by #284
