### ISSUE TITLE
null_resource checks don't work in terraform 0.12

### ISSUE THREAD

**Issue by umairidris** [forseti-security/terraform-google-forseti#212]
null_resource checks like org_id_and_folder_id_are_both_empty don't seem to work anymore in Terraform 0.12. `terraform apply` continues successfully even if none of composite root resources, org id or folder id is set.

**Comment by jdyke** [comment]
Here is what I see when it errors out:

`Error: 2 problems:

- Invalid template interpolation value: Cannot include the given value in a string template: string required.
- Error running command 'echo 'composite_root_resources= org_id= folder_id=' >&2; false': exit status 1. Output: composite_root_resources= org_id= folder_id=`

**Comment by jdyke** [comment]
Hi @umairidris it appears that the variable `org_id` is being set to an empty string but it needs to have a value input from the user. Can you try specifying `org_id` and re-running your plan/apply?
