### ISSUE TITLE
No Forseti command available

### ISSUE THREAD

**Issue by morgante** [forseti-security/terraform-google-forseti#214]
After installing Forseti using the [tutorial](https://github.com/forseti-security/terraform-google-forseti/pull/186), Terraform doesn't show any errors (`terraform apply` succeeds).

But when I SSH into the VM (using `gcloud compute ssh forseti-server-vm-ded1e24f`) the Forseti command is not available.

**Comment by morgante** [comment]
Upon further investigation, it looks like the issue is related to not being able to reach the internet from the VMs created.

From the startup script logs:
```
Jul 31 18:37:52 forseti-server-vm-ded1e24f startup-script: INFO startup-script:   Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.88.24), connection timed out Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.88.162), connection timed out Could not connect to us-east4-c.gce.clouds.archive.ubuntu.com:80 (91.189.91.26), connection timed out
Jul 31 18:37:52 forseti-server-vm-ded1e24f startup-script: INFO startup-script: Err:4 http://us-east4-c.gce.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease
```

Our current default is to launch the VMs without an external IP but this depends on customers having a NAT configured on the network. This is enterprise-friendly but potentially problematic for users who don't have that setup.

**Comment by kevensen** [comment]
@morgante is the note in #217 sufficient to address this issue?

**Comment by morgante** [comment]
@kevensen It would be helpful if someone else could step through the Cloud Shell tutorial and confirm they get a working install (with available Forseti commands) as well.

**Comment by kevensen** [comment]
@morgante The client installation was successful.  However, it appeared that the server didn't install.  I waited for about 10 min then rebooted the VM.  It appears to work now.

**Comment by morgante** [comment]
That's concerning. Could you dig further into why it didn't work the first time?

**Comment by kevensen** [comment]
I am looking in the TTY logs and am seeing 

```bash
Aug 12 17:46:34 forseti-server-vm-e1a2e8c9 startup-script: INFO startup-script: Finished processing dependencies for forseti-security==2.18.0
Aug 12 17:46:35 forseti-server-vm-e1a2e8c9 startup-script: INFO startup-script: AccessDeniedException: 403 forseti-server-gcp-e1a2e8c9@PROJECT.iam.gserviceaccount.com does not have storage.objects.list access to forseti-server-e1a2e8c9.
Aug 12 17:46:35 forseti-server-vm-e1a2e8c9 startup-script: INFO startup-script: Return code 1.
Aug 12 17:46:35 forseti-server-vm-e1a2e8c9 startup-script: INFO Finished running startup scripts.
```
Oddly that SA has the GCS Object Reader permissions.  This is the only glaring issue in the TTY logs.

**Comment by kevensen** [comment]
Not seeing anything in stackdriver or the deployment log.

**Comment by morgante** [comment]
I'm guessing we have a misordered dependency. Let's make sure the server VM is launched *after* the SA is granted all its appropriate roles.

**Comment by morgante** [comment]
As I suspected, it looks like the server VM does not [depend on](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/main.tf#L479) the roles actually being [granted](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/main.tf#L282-L322). We need to add a dependency there.
