### ISSUE TITLE
Investigate data discrepancy issue in Forseti Explainer

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#230]
Looking at IAM, a user has been removed as project/owner (in fact has no privileges, inherited or otherwise).  However, Forseti Explainer is reporting that a user does have the role/owner.

**Comment by morgante** [comment]
Is this a Terraform issue?

**Comment by kevensen** [comment]
Nope.  It is not.  I opened this in the wrong repository.  My apologies.
