### ISSUE TITLE
GCE VMs don't perform any actions when private IP is enabled

### ISSUE THREAD

**Issue by umairidris** [forseti-security/terraform-google-forseti#234]
I made two forseti installations, one with client_private and server_private set to true and one without.

The one without is functioning normally as expected. The one with private IPs correctly has no public IP on the vms, but the VMs themselves don't seem to be doing anything (including running startup scripts). The VMs are just sitting idle and no scans are being done (thus no violations are being reported).

Please see attached logs for info.

[forseti.txt](https://github.com/forseti-security/terraform-google-forseti/files/3536738/forseti.txt)

**Comment by umairidris** [comment]
Note, it also seems like removing the client/server private fields and then running terraform apply causes 5 new resources to be created, but does not fix the problem.

**Comment by ocervell** [comment]
@umairidris when enabling private IP, you'll need to set up a Cloud router + NAT to allow downloading packages from the public internet.

Here is an example with Terraform:

```
data "google_compute_network" "network" {
  name    = "default"
  project = module.forseti-project.project_id
}

data "google_compute_subnetwork" "subnetwork" {
  name    = "default"
  project = module.forseti-project.project_id
  region  = var.forseti_region
}

resource "google_compute_router" "router" {
  name    = "forseti-nat-${terraform.workspace}"
  network = data.google_compute_network.network.self_link
  region  = var.forseti_region
  project = module.forseti-project.project_id
}

module "cloud-nat" {
  source     = "terraform-google-modules/cloud-nat/google"
  project_id = module.forseti-project.project_id
  region     = var.forseti_region
  router     = google_compute_router.router.name
}
```

**Comment by umairidris** [comment]
Sorry haven't had a chance to test it out yet. Will try it tomorrow.

**Comment by ocervell** [comment]
@morgante agreed, let's add an example with the NAT

**Comment by gkowalski-google** [comment]
FYI @kevensen opened [this issue](https://github.com/forseti-security/terraform-google-forseti/issues/254) to provide a working example for a private deployment of Forseti.

**Comment by gkowalski-google** [comment]
I'm going to close this issue since we have #236 and #254 to address the core issues. Thanks @umairidris for creating this issue and providing the suggestions!
