### ISSUE TITLE
Include Config Validator Service 

### ISSUE THREAD

**Issue by callppatel** [forseti-security/terraform-google-forseti#245]
Looks like GKE version of Forseti is not supporting Config Validator. Is there any plan to enhance or this is exitsing bug?

**Comment by morgante** [comment]
Yes, it's being worked on in #229.

**Comment by callppatel** [comment]
Thank you for quick response !

**Comment by dekuhn** [comment]
In the Forseti on GKE Alpha we do address support for config validator. You can find the documentation here: https://forsetisecurity.org/docs/latest/setup/forseti-on-gke.html#deploying-with-config-validator-on-gke
