### ISSUE TITLE
Maintenance window for Cloud SQL DB

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#249]
Got a request for a customer to have the ability to have a maintenance window for Cloud SQL DB upgrades. 

Context: We are adding the possibility to config-validator to check for a specific maintenance window for all Cloud SQL DBs deployed on GCP (see [PR #161](https://github.com/forseti-security/policy-library/pull/161)) and the Forseti db pops up in the violations.

Implementation can look like this:

```hcl
  settings {
   ...
   maintenance_window {
      day = var.maintenance_window.day
      hour = var.maintenance_window.hour
      update_track = var.maintenance_window.update_track
   }
  }
```
```hcl
variable "maintenance_window" {
    description = "Configuration of a maintenance window for Forseti's CloudSQL DB"
    type = object({
        day = number
        hour = number
        update_track = string
    })
    default = {
        day = null
        hour = null
        update_track = stable
    }
}
```

**Comment by morgante** [comment]
This makes sense to me, happy to look at a PR.
