### ISSUE TITLE
Eliminate the need for the IAM SA keys as Kubernetes secrets

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#250]
It is a best practice not to use security key (whenever possible). But currently for Forseti on GKE, IAM service account key is obtained from GCP and added as a secret to kubernetes.

Per discussion with @kevensen, it is possible to create a dedicated Forseti nodepool in the cluster and bind the SA to the nodes, without using a key.  i.e. "taint" these nodes as described above for the sole-use of Forseti.

**Comment by morgante** [comment]
Instead of using a dedicated node pool, could we use workload identity? https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by blueandgold** [comment]
Workload identity sounds like an interesting idea.  Would love to use it if it will solve not having to use a key.  @kevensen FYI

**Comment by kevensen** [comment]
I like that idea.  This feature is still in beta.  I'd like to make an update to the terraform-google-kubernetes-engine module.  Any concerns?

**Comment by morgante** [comment]
I'm happy to look at a PR for Kubernetes.

**Comment by kevensen** [comment]
Okeedokee.  I'll start there.

**Comment by kevensen** [comment]
@morgante https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/266

**Comment by morgante** [comment]
Apologies, it looks like this was already added to the GKE module: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/234

You should be able to use it directly once the next module is released: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/CHANGELOG.md#added

**Comment by kevensen** [comment]
No worries.  It was good practice.  I'll look forward to the next release.

**Comment by gkowalski-google** [comment]
@kevensen Was this addressed with the work for the GKE beta release?

**Comment by kevensen** [comment]
Yes
