### ISSUE TITLE
Expose disk type for Cloud SQL

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#252]
Allow users to set the disk type for the Cloud SQL instance, similar to how you can do this for the Forseti server.

Moved this issue from the main Forseti repo: https://github.com/forseti-security/forseti-security/issues/2591.

**Comment by kevensen** [comment]
I think this may be addressed by https://github.com/forseti-security/terraform-google-forseti/pull/228.  Though it only exposes the disk size and not the type.  Default is SSD.

**Comment by gkowalski-google** [comment]
> I think this may be addressed by #228. Though it only exposes the disk size and not the type. Default is SSD.

Thanks! I have updated this issue to just be for the disk type.

**Comment by kevensen** [comment]
The challenge I was having is that the disk type parameter for CloudSQL is an ENUM and Terraform wasn't taking that kindly.

**Comment by morgante** [comment]
ENUMs are simply strings in Terraform, do you have more details?

**Comment by kevensen** [comment]
No, just tragic memories.  It was probably due to my unfamiliarity with how various variable values are represented.  I'll give it another go and let you know if I have any trouble.

**Comment by gkowalski-google** [comment]
Closing #16 since these are the same. Some more context for this issue:

https://github.com/forseti-security/terraform-google-forseti/pull/14#discussion_r225728951
