### ISSUE TITLE
Provide a Complete Configuration for a Private Deployment of Forseti

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#254]
This purpose of this issue is to capture tasks necessary to provide a working deployment of Forseti in a private configuration.

* Private server and client: #31 and #76 
* Private CloudSQL: #228

Tasks:
Create an example that includes the following:
- [x] CloudNAT
- [ ] Bastion Host
- [ ] Configures master authorized networks for GKE
- [x] Sets all the pertinent variables to private w/o user input: server_private, client_private, cloudsql_private

**Comment by gkowalski-google** [comment]
Please see [Forseti Issue #3186](https://github.com/forseti-security/forseti-security/issues/3186) for some helpful information from someone trying to setup Forseti privately. There is one potential issue with the Blacklist Scanner, which attempts to download a list of blacklisted IPs. This will fail with a private deployment.

**Comment by Red-Five** [comment]
Bastion host no longer needed. Ref. https://cloud.google.com/iap/docs/using-tcp-forwarding

**Comment by morgante** [comment]
Note a bastion host is likely still required for connecting to a private GKE cluster.

**Comment by Red-Five** [comment]
> Note a bastion host is likely still required for connecting to a private GKE cluster.

Ahh :) It might be necessary to spin up a small 'admin' vm on the network in same region as cluster to be able to run kubectl (if not using master authorized network). It would not be a traditional bastion as it won't need a public endpoint.

**Comment by kevensen** [comment]
@Red-Five I think it will need a public endpoint if you want to SSH to it.

**Comment by Red-Five** [comment]
> @Red-Five I think it will need a public endpoint if you want to SSH to it.

The SSH button on Cloud Console now works automatically with private IP only VM's via IAP.

**Comment by kevensen** [comment]
Well that's neat.

**Comment by gkowalski-google** [comment]
Pick up from Ken's closed PR, add tests, and ensure it's working with the latest production module.
