### ISSUE TITLE
Update on-gke examples to TF 12

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#267]
The on-gke examples are still using tf 0.11 syntax.

**Comment by gkowalski-google** [comment]
Some notes I have about these examples after going through them in testing:

- Update to use the `GOOGLE_APPLICATION_CREDENTIALS` env var for credentials, and don't make `credentials_path` required.
- Update the Policy Library URL to use git protocol, e.g. `git@github.com:forseti-security/policy-library`
- The examples display warnings about the use of region being deprecated and that location should be used instead.

**Comment by gkowalski-google** [comment]
@kevensen Was this addressed with the work for GKE beta release?

**Comment by kevensen** [comment]
Yes
