### ISSUE TITLE
The Cloud SQL instance needs to get recreated, and will fail, during upgrade to terraform-google-forseti v4.2.0

### ISSUE THREAD

**Issue by katze120** [forseti-security/terraform-google-forseti#271]
The Cloud SQL instance needs to get recreated, and will fail, during upgrade to terraform-google-forseti v4.2.0
I'm guessing the reason it needs recreation is that [there was major restructuring of sql sub-module in terraform-google-forseti](https://github.com/forseti-security/terraform-google-forseti/pull/228) between the 2nd last release and the latest release v2.21.0.
The recreation with the same Cloud SQL instance name will fail because [You cannot reuse an instance name for up to a week after you have deleted an instance.](https://cloud.google.com/sql/docs/mysql/delete-instance)

I don't have concrete proposal on how best to solve this, but raising an issue for awareness first.
Some possible solution is: if we know db will be created, add an additional suffix to ensure db instance name is unique

**Comment by kevensen** [comment]
@katze120 Thanks for raising the issue.  If you run `terraform plan` can you please identify the attributes that are triggering the change?  I don't think we "need" to create a new CloudSQL instance so I'd like to understand why Terraform does.

**Comment by kevensen** [comment]
@katze120 I re-read your issue description.  No further clarification is required at this time.  We are investigating this now.

**Comment by gkowalski-google** [comment]
@katze120 Thank you very much for raising this issue! Are you aware of any users who have been affected? Please let me know and I will work with them to get this resolved. The v4.2.0 module has been deleted and we are working on publishing a new minor version of the module without these breaking changes.

**Comment by gkowalski-google** [comment]
Resolved by @kevensen, new [module release 4.2.1](https://github.com/forseti-security/terraform-google-forseti/releases/tag/v4.2.1).
