### ISSUE TITLE
Reduce privileges

### ISSUE THREAD

**Issue by morgante** [forseti-security/terraform-google-forseti#28]
https://github.com/GoogleCloudPlatform/forseti-security/pull/2395

**Comment by kevensen** [comment]
@morgante with #2395 merged, can this be closed?

**Comment by morgante** [comment]
I believe we also have to make the associated update on this module.

**Comment by kevensen** [comment]
Gotcha.  I can tackle that.

**Comment by kevensen** [comment]
@morgante, it looks like #210 addresses this.

**Comment by morgante** [comment]
Thanks, indeed it does.
