### ISSUE TITLE
Services `opa-policy` and `enforcer` failed to start in `real_time_enforcer` test

### ISSUE THREAD

**Issue by paulpalamarchuk** [forseti-security/terraform-google-forseti#285]
`opa-server.service` and `enforcer.service` failed to start on startup during integration tests `real_time_enforcer`
![image](https://user-images.githubusercontent.com/15910313/65972591-bc6a5280-e472-11e9-90d3-8ee779cfd441.png)

**Comment by morgante** [comment]
As we told the team last week, failing tests should be temporarily disabled.

**Comment by gkowalski-google** [comment]
@paulpalamarchuk @morgante Anything else to do here or can we close this?

**Comment by morgante** [comment]
This still needs to be fixed, currently the real-time enforcer tests are disabled: https://github.com/forseti-security/terraform-google-forseti/blob/master/.kitchen.yml#L121
