### ISSUE TITLE
Ubuntu Security Updates are failing to install

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#286]
## Story
In some cases Forseti startup script fails to complete because an Ubuntu security update fails to install. In this case Ubuntu is fail to acquire a lock to install the package.

`
Oct  1 08:45:25 forseti-server-vm-c0366c40 startup-script: INFO startup-script: Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [608 kB]
Oct  1 08:45:30 forseti-server-vm-c0366c40 startup-script: INFO startup-script: Fetched 3143 kB in 3s (989 kB/s)
Oct  1 08:45:32 forseti-server-vm-c0366c40 startup-script: INFO startup-script: Reading package lists...
Oct  1 08:45:33 forseti-server-vm-c0366c40 startup-script: INFO startup-script: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
Oct  1 08:45:33 forseti-server-vm-c0366c40 startup-script: INFO startup-script: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Oct  1 08:45:33 forseti-server-vm-c0366c40 startup-script: INFO startup-script: Return code 100.
Oct  1 08:45:33 forseti-server-vm-c0366c40 startup-script: INFO Finished running startup scripts.
`

## Proposed Solution
Determine if there is a good way to attempt to to install the Ubuntu security updates and continue Forseti setup process even if these failures happen. Investigate why Ubuntu is failing to install this particular update (see if it can be reproduced) and implement a change in the startup script to prevent this error from happening.

## Acceptance Criteria

- Forseti always starts up, even if a security update fails to install

**Comment by dlinares-linux** [comment]
I have reproduced the issue today and might have found something in the logs which might explain my issue:
```
...
Oct  2 10:53:26 forseti-server-vm-e8613759 startup-script: INFO startup-script: Get:15 http://europe-west2-c.gce.clouds.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7556 B]
Oct  2 10:53:28 forseti-server-vm-e8613759 systemd[1]: Started Daily apt download activities.
Oct  2 10:53:28 forseti-server-vm-e8613759 systemd[1]: Starting Daily apt upgrade and clean activities...
Oct  2 10:53:29 forseti-server-vm-e8613759 startup-script: INFO startup-script: Fetched 2853 kB in 3s (1021 kB/s)
Oct  2 10:53:31 forseti-server-vm-e8613759 startup-script: INFO startup-script: Reading package lists...
Oct  2 10:53:31 forseti-server-vm-e8613759 startup-script: INFO startup-script: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
```
So it looks like there is a clash between the apt-daily.service and the start-up script doing updates at the same time.

**Comment by dlinares-linux** [comment]
Linking to this issue: https://github.com/GoogleCloudPlatform/compute-image-packages/issues/815
From the comments, it looks like the issue has been fixed but not yet made available to Ubuntu.

**Comment by gkowalski-google** [comment]
@hshin-g Can you please review the PR? I think this is a good change to make.

**Comment by bvandewalle** [comment]
You can use the same workaround described in the issue linked above in the meantime

**Comment by gkowalski-google** [comment]
@kevensen Assigning this to you since you will be on support next week. I have approved the PR and think this is a good change, can you help us get this over the finish line?

**Comment by kevensen** [comment]
@gkowalski-google, which PR?  #275?

**Comment by gkowalski-google** [comment]
> @gkowalski-google, which PR? #275?

Yes that is the one.

**Comment by kevensen** [comment]
@gkowalski-google ok to close?

**Comment by gkowalski-google** [comment]
> @gkowalski-google ok to close?

Yes I think it's fine to close this. As long as Forseti is started ONCE with this updated command, then if security updates fail in the future, Forseti will still start. However, if they fail to install before Forseti can run once, then we'll still have an issue. I think it's ok to wait for the official fix instead of implementing the workaround, unless more users start to run into this.
