### ISSUE TITLE
Kitchen tests uses same keyfile for 2 tests: "simple_example" and "shared_vpc"

### ISSUE THREAD

**Issue by paulpalamarchuk** [forseti-security/terraform-google-forseti#289]
Module `bastion` generates 2 different keys for fixture modules "simple_example" and "shared_vpc", but places them to the same file `test/fixtures/bastion/tls_private_key`. That causes verification to fail for the test, that created earlier, in case tests called in one scope.

**Comment by gkowalski-google** [comment]
This can be solved by using the Bastion Host example/module by using OS Login, instead of using private keys.
