### ISSUE TITLE
Client Configuration is not updated when Server IP changes

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#295]
## Story
Sometimes when the Forseti Server VM is replaced, the Client configuration is not updated to use the new Forseti Server IP. I have seen cases where the Client and Server VM get replaced at the same time, but existing Client configuration still points to the old IP. To fix, users have to manually run `forseti config endpoint {SERVER_IP}:50051` from the client to fix.

## Proposed Solution
Instead of using the server IP address, use the [internal DNS](https://cloud.google.com/compute/docs/internal-dns) of the server. By default GCE instances have a zonal DNS available like `forseti-server-vm-{SUFFIX}.us-central1-c.c.forseti-test123.internal`. Update the client config module to use for the server IP instead of the actual IP.

## Acceptance Criteria
GIVEN: Forseti is deployed on GCE with Terraform
WHEN: Terraform recreates the Forseti Server VM
THEN: The Forseti Client VM always has the correct Server IP

**Comment by kevensen** [comment]
GKE will take a little more thought.  Right now, there is an annotation in the forseti-server K8s service which GKE recognizes, and tells GCP to spin up an internal or external load balancer depending on the user's choice.

https://github.com/forseti-security/helm-charts/blob/master/charts/forseti-security/templates/server/service.yaml

The internal DNS in a GCP VPC does provide DNS records for ILB's in the format of `[SERVICE_LABEL].[FORWARDING_RULE_NAME].il4.[REGION].lb.[PROJECT_ID].internal`.  The gotcha here is the `SERVICE_LABEL` which can't be set from a K8s service.

**Comment by gkowalski-google** [comment]
Create a corresponding ticket for GKE

**Comment by blueandgold** [comment]
@allisonis  for FYI, who reported this issue before.
