### ISSUE TITLE
Make ORG_ID in setup.sh more resilient

### ISSUE THREAD

**Issue by morgante** [forseti-security/terraform-google-forseti#3]
Right now it requires users to input the ORG_ID manually, would be nice to grab it from PROJECT_ID.

See a discussion on this here: https://github.com/terraform-google-modules/terraform-google-forseti/pull/2/files/c6a9ac706fd60fc0179dfdd4870f3b54cb0aa046#r205215428

**Comment by dekuhn** [comment]
There is a PR on this issue is there still more work required for this?
