### ISSUE TITLE
Warning: "region": [DEPRECATED] Use location instead

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/terraform-google-forseti#303]
Running terraform-google-modules/forseti/google//examples/on_gke_end_to_end
generates various warnings

Warning: "region": [DEPRECATED] Use location instead
Warning: "zone": [DEPRECATED] Use location instead

**Comment by kevensen** [comment]
Indeed it does.  This actually has to do with the terraform-google-kubernetes-engine module (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/259).  I believe the desire is to remain explicit about the location of the GKE cluster via region and zones.

**Comment by gkowalski-google** [comment]
Confirmed Forseti is using 5.0.0 of the Kubernetes module, re-open if the warnings are still seen.
