### ISSUE TITLE
Support DB username and password in GKE

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#315]
As a user of Forseti on-GKE, I would like to be able to access the SQL DB with a user name and password in order to assert authentication to the database.

- [ ] https://github.com/forseti-security/helm-charts/issues/43
- [ ] Pass the sql_db_user to the helm_release resource
- [ ] Pass the sql_db_password to the helm_release resource

**Comment by joecheuk** [comment]
Resolved in:
https://github.com/forseti-security/helm-charts/pull/52
and 
https://github.com/forseti-security/terraform-google-forseti/pull/318
