### ISSUE TITLE
Cloudshell Installer should use latest version and be exposed through tfvars file

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/terraform-google-forseti#321]
The Cloudshell Installer is currently using the syntax `~>3.0.0` which means that users would only be using version =3.0.0, <4.0.0. 

Proposed change is to use '>=' instead to always pull in the latest version for users.

Additionally, the `version` should be available in the `terraform.tfvars` file so users are able to see what minimum version they are using vs. being obfuscated. 

@blueandgold

**Comment by morgante** [comment]
I wouldn't suggest an opened version constraint as users shouldn't be upgraded unexpectedly.

Instead, we should probably just update the installer with each major release.

**Comment by gkowalski-google** [comment]
@hshin-g @blueandgold I have updated our release docs to include this as a step, can we close this out?
