### ISSUE TITLE
Ensure Server VM & CloudSQL are Deployed Together

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#334]
For a more performant inventory, the Server VM and the CloudSQL should be deployed together in the same region.

But, in the Simple Install, the `region` value in terraform.tfvars would allow the server vm to be deployed to a different region (either as the default or as user-specified) from the cloudsql region (which is us-centra1).

Essentially, the `terraform.tfvars` of simple install needs to be updated with:
```
cloudsql_region = "us-central1"
server_region   = "us-central1"
client_region   = "us-central1"
```

![image](https://user-images.githubusercontent.com/6977544/67172378-fc38a180-f36f-11e9-8320-02a224a66383.png)

**Comment by gkowalski-google** [comment]
This can be done from the [main.tf](https://github.com/forseti-security/terraform-google-forseti/blob/master/examples/install_simple/main.tf#L25) by setting `cloudsql_region` to var.region as well.
