### ISSUE TITLE
Missing Config in forseti_conf_server.yaml After Migrating from Python Installer

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#336]
Just tried this one when migrating from 2.18 to 2.23, and the `email_connector` info is not found in the new `forseti_conf_server.yaml` file, even though it was specified in the `main.tf`.

Should also see if there are others.

![image](https://user-images.githubusercontent.com/6977544/67260652-52c9dc80-f451-11e9-8bf2-bb7fd800925a.png)

**Comment by blueandgold** [comment]
No issue with the upgrade of v2.22 to v2.23.

**Comment by hshin-g** [comment]
@blueandgold If a Sendgrid API key is not provided, then that field will not populate. Refer here: https://github.com/forseti-security/terraform-google-forseti/blob/045c0987b585cc3f37710584ca5e6530bb596740/modules/server_config/templates/configs/forseti_conf_server.yaml.tpl#L281-L289

**Comment by blueandgold** [comment]
Indeed this is the cause.  After I added the customized fields, then the config shows up.
