### ISSUE TITLE
Finish Updating the Comments for PR #333.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#338]
Ken is OOO today.  @red2k18 will take this over and finish addressing the comments.

**Comment by hshin-g** [comment]
@blueandgold Can this issue be closed?

**Comment by blueandgold** [comment]
@red2k18 please link to your PR and close this.  Thanks.

**Comment by red2k18** [comment]
#347 resolved comments from #333.
