### ISSUE TITLE
Make the Options for Policy Library Sync to Be Consistent

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/terraform-google-forseti#341]
@blueandgold commented on [Sat Oct 19 2019](https://github.com/forseti-security/policy-library/issues/190)

On GCE, this is off by default, and needs `policy_library_sync_enabled = true` to be set.

On GKE, this is on by default, and `policy_library_sync_enabled` is not exposed to be configure-able.

Since there is a case for continued usage of GCS buckets, a couple of things need to be done:
1: `policy_library_sync_enabled` needs to be configure-able on GKE in case GCS is prefered
2: make consistent the default behavior whether it's on or off, on both GCE and GKE

This needs to be implemented with the corresponding [Helm issue](https://github.com/forseti-security/helm-charts/issues/38).

**Comment by dekuhn** [comment]
We will disable this feature on GKE by default in 2.23 release. If someone wants to use CV + Policy Library they can explicating enable this feature.

GCS sync support on GKE needs to be added. Our default out of the box behavior on GCE/GKE should be GCS Sync.

**Comment by kevensen** [comment]
Closed via #356
