### ISSUE TITLE
Install Forseti Server/CloudSQL to Same Zone

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#343]
Currently, even when the same region is specified, the Forseti server could be installed to a different zone from the CloudSQL.  This will make a difference in inventory performance.

For 300K resources, inventory time is:

server & cloudsql in different zones: 13 minute
server & cloudsql in same zone: 12 minutes

If this difference is significant enough, we should ensure both the server and cloudsql are deployed to the same zone.

Relates to #334

**Comment by gkowalski-google** [comment]
This change was [previously implemented](https://github.com/forseti-security/terraform-google-forseti/pull/253), but looks like it was lost in the sub-modularization efforts. I will get this change back in this morning for the 2.23.0 release.
