### ISSUE TITLE
Disable the Policy Library Sync on GKE until It Supports Storing on GCS

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/terraform-google-forseti#344]
This is a follow-up issue for #341 . So, on the 2.23 release, policy libraries are synced from git repo as a default, and does not support sync with GCS Bucket, which is inconsistent to the GCE version, and we want GCS to be the default option.  So, disable policy library sync on GKE, until it supports GCS.

**Comment by gkowalski-google** [comment]
Disabling the policy library sync would make CV unusable since there would be no way to provide constraints.

**Comment by blueandgold** [comment]
@gkowalski-google yes, this is the side-effect of this change.

**Comment by morgante** [comment]
@blueandgold I don't think we should cause a regression for GKE customers just because GCE doesn't support gir-sync yet.

**Comment by kevensen** [comment]
@morgante Point of clarification.  GCE supports Git and GCS for policy-library.  GKE only supports Git.  The initial thought was that yes, customers would only be using Git so that was all that was implemented in GKE.

**Comment by kevensen** [comment]
Implementing the enable/disable of git-sync for GKE actually will happen in the Helm charts.  This variable will need to be implemented there.  But, let's do that in the context of implementing GCS as an option as well for the policy-library.

**Comment by kevensen** [comment]
https://github.com/forseti-security/helm-charts/issues/38

**Comment by gkowalski-google** [comment]
We discussed this some more. We will not disable the policy library sync feature from working on GKE and the GCS sync will be implemented for the 2.24 release.

@morgante Regarding the default option, I agree that the VCS is the better approach. I think that some customers will not want to expose their internal repos and this approach requires more work by the user. The GCS option doesn't require any up-front work for the user. I think we should continue recommending to users the VCS sync, but if they have not set anything up then they can still use CV out of the box.
