### ISSUE TITLE
Error when setting the CloudSQL instance to be private

### ISSUE THREAD

**Issue by dlinares-linux** [forseti-security/terraform-google-forseti#359]
# Story

This issue is raised as a follow up of #296 .
Following the 5.0.0 release, I have upgraded to 5.0.0 and forseti v2.23.0.
When setting cloudsql_private = true, I am getting the following issue:
```
Error: Error waiting for Create Service Networking Connection: Error code 9, message: Cannot modify allocated ranges in CreateConnection. Please use UpdateConnection.

  on .terraform/modules/forseti/forseti-security-terraform-google-forseti-1ef45bf/modules/cloudsql/main.tf line 53, in resource "google_service_networking_connection" "private_vpc_connection":
  53: resource "google_service_networking_connection" "private_vpc_connection" {
```

Could it be related to terraform-providers/terraform-provider-google#3294 and terraform-providers/terraform-provider-google-beta#1240 ?
Or is there something wrong with my setup? For example, my setup uses the same project for the network and forseti.

# My set-up

- Forseti and Network deployed in the same project
- Fresh install from terraform module 5.0.0, previous install has been destroyed
- Using Forseti on GCE for now (planning to move to GKE soon)
- Client/Server and CloudSQL set to private

**Comment by kevensen** [comment]
@dlinares-linux If you could answer a couple questions.

1. Are you upgrading from a previous version of Forseti (or is this a fresh install)
2. Are you deploying Forseti on-GCE or on-GKE

**Comment by dlinares-linux** [comment]
Just modified the description to add some info about my set up.
Happy to share some code if that helps.
Cheers, David

**Comment by kevensen** [comment]
@dlinares-linux Yes, if you cloud please share your main.tf, that would be helpful.  Also, you indicated that the previous install had been destroyed.  Did you remove your terraform.tfstate file?

**Comment by dlinares-linux** [comment]
Hi @kevensen 
Below is the equivalent of my main.tf (just gathered everything together).
```
# create vpc
resource "google_compute_network" "vpc_forseti" {
  project                         = google_project.forseti_project.project_id
  name                            = "${var.org_name}-vpc-forseti"
  auto_create_subnetworks         = false
  delete_default_routes_on_create = true
  routing_mode                    = "REGIONAL"

  depends_on = ["google_project.forseti_project"]
}

# create private subnet
resource "google_compute_subnetwork" "subnet_forseti" {
  project                  = google_project.forseti_project.project_id
  name                     = "subnet-${google_compute_network.vpc_forseti.name}"
  ip_cidr_range            = "10.2.2.0/24"
  network                  = google_compute_network.vpc_forseti.name
  region                   = var.region
  private_ip_google_access = true
  enable_flow_logs         = true

  depends_on = ["google_compute_network.vpc_forseti"]
}

# Router to give private instances a route to the internet
resource "google_compute_router" "router_forseti" {
  name    = "router-forseti"
  region  = var.region
  network = google_compute_network.vpc_forseti.name
  project = google_project.forseti_project.project_id

  bgp {
    asn = 64515
  }
}

resource "google_compute_route" "default" {
  project          = google_project.forseti_project.project_id
  name             = "default-network-route"
  dest_range       = "0.0.0.0/0"
  network          = google_compute_network.vpc_forseti.name
  priority         = 1000
  next_hop_gateway = "default-internet-gateway"
}

resource "google_compute_router_nat" "nat_forseti" {
  name                               = "nat-1-forseti"
  router                             = google_compute_router.router_forseti.name
  region                             = var.region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
  project                            = google_project.forseti_project.project_id
}

module "forseti" {
  source                   = "terraform-google-modules/forseti/google"
  version                  = "5.0.0"
  forseti_version          = "v2.23.0"
  gsuite_admin_email       = var.gsuite_admin_email
  domain                   = var.domain
  project_id               = var.forseti_project_id
  org_id                   = var.org_id
  storage_bucket_location  = var.region
  bucket_cai_location      = var.region
  client_region            = var.region
  client_private           = true
  server_region            = var.region
  server_private           = true
  cloudsql_region          = var.region
  cloudsql_private         = true
  network                  = google_compute_network.vpc_forseti.name
  subnetwork               = google_compute_subnetwork.subnet_forseti.name
  network_project          = var.forseti_project_id
  config_validator_enabled = true
  cscc_violations_enabled  = true
  cscc_source_id           = var.cscc_source_id
  forseti_run_frequency    = var.forseti_run_frequency
  manage_rules_enabled     = false
}
```

**Comment by kevensen** [comment]
@dlinares-linux Thanks for providing this information.   Nothing jumps out at me.  Could you please execute `terraform providers` in your root module and provide the versions of the `google` and `google-beta` provider?

**Comment by dlinares-linux** [comment]
Hi @kevensen ,
Here is the result:

```
.
├── provider.google
├── provider.template
├── provider.terraform
├── module.forseti
│   ├── provider.google (inherited)
│   ├── provider.null ~> 2.0
│   ├── provider.random ~> 2.0
│   ├── provider.template ~> 2.0
│   ├── module.client
│   │   ├── provider.google (inherited)
│   │   ├── provider.null
│   │   └── provider.template
│   ├── module.client_config
│   │   ├── provider.google (inherited)
│   │   └── provider.template
│   ├── module.client_gcs
│   │   ├── provider.google (inherited)
│   │   └── provider.null
│   ├── module.client_iam
│   │   └── provider.google (inherited)
│   ├── module.cloudsql
│   │   ├── provider.google (inherited)
│   │   └── provider.null
│   ├── module.server
│   │   ├── provider.google (inherited)
│   │   ├── provider.null
│   │   ├── provider.random
│   │   ├── provider.template
│   │   └── provider.tls
│   ├── module.server_config
│   │   ├── provider.google (inherited)
│   │   ├── provider.null
│   │   └── provider.template
│   ├── module.server_gcs
│   │   ├── provider.google (inherited)
│   │   └── provider.null
│   ├── module.server_iam
│   │   └── provider.google (inherited)
│   └── module.server_rules
│       ├── provider.google (inherited)
│       └── provider.template

```

As for the version, I can see terraform-provider-google_v2.18.0_x4 in the directory .terraform/plugins/darwin_amd64/

**Comment by kevensen** [comment]
@dlinares-linux Thanks for providing that.  Could you please try setting the `google` provider to **2.11**?
```
provider "google" {
  version = "~> 2.11.0"
  project = var.project_id
}
```

**Comment by dlinares-linux** [comment]
Thanks a lot @kevensen .
I am deploying in europe-west2.
Cheers,
David

**Comment by dlinares-linux** [comment]
Hi @kevensen ,
I am not really upgrading, as I have run:
- `terraform destroy --auto-approve`
- `rm -rf .terraform`
- `terraform init`
- `terraform apply --auto-approve`
But for your info, the version I had before was terraform module 4.2.1 and forseti v2.21.0

**Comment by kevensen** [comment]
@dlinares-linux I have tested the main.tf you provided.  I was able to successfully deploy Forseti 2.23 with version 5.0.0 of the terraform-google-forseti module.

Can you please execute `terraform --version` in your module directory and provide the output?

**Comment by dlinares-linux** [comment]
Hi @kevensen ,
Sorry for the slow reply, that's interesting.
So, I am using terraform v0.12.6.
With the exact same code, when I destroy my infra, upgrade to terraform v0.12.13, re-apply, I am now getting the following error:
```
  on .terraform/modules/forseti/forseti-security-terraform-google-forseti-1ef45bf/modules/server/outputs.tf line 19, in output "forseti-server-git-public-key-openssh":
  19:   value       = tls_private_key.policy_library_sync_ssh[0].public_key_openssh
    |----------------
    | tls_private_key.policy_library_sync_ssh is empty tuple

The given key does not identify an element in this collection value.
```
Happy to open a new issue, as it seems to be related to the fact that I haven't set   policy_library_sync_enabled = true in my config.

Anyway, going back to the original issue, after upgrading to terraform v0.12.13 and setting policy_library_sync_enabled = true to workaround the issue above, I am still getting the same issue: 
```
Error: Error waiting for Create Service Networking Connection: Error code 9, message: Cannot modify allocated ranges in CreateConnection. Please use UpdateConnection.

  on .terraform/modules/forseti/forseti-security-terraform-google-forseti-1ef45bf/modules/cloudsql/main.tf line 53, in resource "google_service_networking_connection" "private_vpc_connection":
  53: resource "google_service_networking_connection" "private_vpc_connection" {
```

**Comment by kevensen** [comment]
@dlinares-linux The tls-key issue is a known issue and will be fixed in terraform-google-forseti 5.1.0.

Let's try this.  Can you please move your _terraform.tfstate*_ files to another directory or remove them all together?

**Comment by dlinares-linux** [comment]
Hi @kevensen ,
Finally got some info which I hope would be useful.

When upgrading to terraform 0.12.13 and running the code as above, the first tls-key issue is leaving the system in a weird state. The private_vpc_connection stays in the tfstate, even after a destroy. I need to call  `terraform destroy` twice to clean the tfstate properly.
After that, when adding `policy_library_sync_enabled = true` and applying, it worked fine!

**Comment by kevensen** [comment]
@dlinares-linux My hypothesis was that something was stuck in the _terraform.tfstate_ file.  I am glad you were able to resolve the issue.  Is it ok to close?

**Comment by dlinares-linux** [comment]
Yes. 
Thank you so much for your help @kevensen !

**Comment by kevensen** [comment]
@dlinares-linux My pleasure.  Please let me know if you have further questions.
