### ISSUE TITLE
Specify the micro version of TF binary in all versions.tf

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#364]
Right now, the specified version of TF is specified as `0.12`.  There have been issues between micro versions.

We should consider posting the supported TF version (with micro version) in the release notes as well as release communications.

**Comment by morgante** [comment]
We should be able to specify the micro version in versions.tf: https://www.terraform.io/docs/configuration/terraform.html#gt--1

**Comment by kevensen** [comment]
I misunderstood a conversation I had with @aaron-lane.  If we can fix the micro version here, then my two cents is that we should.  We also would like to be consistent with the rest of CFT.  @morgante would we create a conflict if we set the micro version here and the rest of the CFT modules didn't?

**Comment by morgante** [comment]
Nope, that's fine.

**Comment by red2k18** [comment]
Pinning a specific minor Terraform version is discouraged as this will make users lives much harder; they won't be able to update to a new Terraform version (even for other modules). No other CFT or reusable modules do this, and HashiCorp strongly discourages it.
