### ISSUE TITLE
Forseti can not be installed with policy_library_sync_enabled = false

### ISSUE THREAD

**Issue by marko7460** [forseti-security/terraform-google-forseti#367]
1. Installing fresh forseti 
1. ```hcl
   module "forseti" {
    source                   = "git@github.com:forseti-security/terraform-google-forseti.git?ref=v5.0.0"
    gsuite_admin_email       = var.gsuite_admin_email
    domain                   = var.domain
    project_id               = module.secops.project_id
    org_id                   = var.org_id
    network                  = module.forseti-vpc.network_name
    subnetwork               = module.forseti-vpc.subnets_names[0]
    client_private           = true
    client_region            = var.region
    server_private           = true
    server_region            = var.region
    server_grpc_allow_ranges = ["10.10.10.0/24"]
    cloudsql_private         = true
    cloudsql_region          = var.region
    bucket_cai_location      = var.region
    storage_bucket_location  = var.region
   }
   ```
1. terraform init
1. terraform plan

Result:
```Error: Invalid index

  on .terraform/modules/forseti/modules/server/outputs.tf line 19, in output "forseti-server-git-public-key-openssh":
  19:   value       = tls_private_key.policy_library_sync_ssh[0].public_key_openssh
    |----------------
    | tls_private_key.policy_library_sync_ssh is empty tuple

The given key does not identify an element in this collection value.
```

Analysis:
This resource https://github.com/forseti-security/terraform-google-forseti/blob/v5.0.0/modules/server/main.tf#L174-L177 will not be created when `policy_library_sync_enabled = false`. The output should be something like this:

```hcl
output "forseti-server-git-public-key-openssh" {
  description = "The public OpenSSH key generated to allow the Forseti Server to clone the policy library repository."
  value       =  var.policy_library_sync_enabled ? tls_private_key.policy_library_sync_ssh[0].public_key_openssh : null
}
```

**Comment by paskal** [comment]
I believe it was fixed in #362.

**Comment by marko7460** [comment]
Closing.

**Comment by dekuhn** [comment]
@kevensen @gkowalski-google I assume we need to label this issue related to the release in which we caused this issue. Can we please label accordingly?
