### ISSUE TITLE
`Cloud Asset Viewer` Role not assigned on Composite Root Resources

### ISSUE THREAD

**Issue by garrettwong** [forseti-security/terraform-google-forseti#375]
roles/cloudasset.viewer is not assigned on the Composite Root Resource node.  Have done two project deployments using the variable, and post-deployment, the role binding does not exist on the Project.

```bash
module "forseti" {
    source  = "terraform-google-modules/forseti/google"
    # other vars ....

    composite_root_resources = ["projects/${PROJECT_ID}"]
}
```

I haven't had a chance to confirm it yet, but assuming that the module only accounts for applying this role on the Organization.

**Comment by gkowalski-google** [comment]
@garrettwong Did the service account have the org level asset view role?

**Comment by red2k18** [comment]
@garrettwong any update on this?

**Comment by gkowalski-google** [comment]
Investigate if we can automate this within Terraform for the various composite root resources (org/folder/project). If not, then document what someone will need to do when using composite root.

**Comment by garrettwong** [comment]
The service account did not have any Org Level roles.  My assumption for composite_root_node for a project is that the user installing does not have Org or Folder level roles, but has enough Project level roles for installation.
