### ISSUE TITLE
Explore how to lock Forseti version

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#387]
## Story
The version of Forseti deployed with the Terraform module is a variable that users can control. However some versions of Forseti are known to be non-compatible with some versions of the Terraform module. Determine what is the best way to lock the Forseti version in for certain module versions, while still giving the flexibility to choose a "special" version of Forseti. For example, some use cases for testing purposes will always want the master branch of Forseti installed, and some scenarios might need to deploy a branch/tag/release of Forseti other than the default version.

**Comment by blueandgold** [comment]
One approach would be to have an installer (that wraps terraform) that can
to do this.

**Comment by kevensen** [comment]
I'd like to suggest a simpler approach.  Provide a shell script that asks some basic questions and then generates a main.tf.  One of the input cloud be the Forseti version.  The script would then set the terraform-google-forseti module version accordingly.

**Comment by morgante** [comment]
I'd strongly discourage building additional tooling on top of Terraform, it mostly just makes things too brittle.

How much of an issue is this for customers in reality? It seems like pinning the default version with the variable + *optionally* allowing an override should solve for 90% of cases.

**Comment by gkowalski-google** [comment]
We have a change upcoming that we know will not be compatible unless users are on the correct versions. It's likely not a huge issue, but we don't know how everyone is using Terraform today. This seemed like a good thing to do to ensure users do not run into any issues.

**Comment by morgante** [comment]
I'm not sure if it's worth adding complexity if it's just a hypothetical. We've always encouraged pinning to a minor module version and presumably the new (breaking) Forseti release should be a new module version, so it's only an issue if people *explicitly* set the new `forseti_version` *without* upgrading the module version—which we have documented is unsupported.
