### ISSUE TITLE
Update to the latest version of the Google Provider

### ISSUE THREAD

**Issue by kevensen** [forseti-security/terraform-google-forseti#388]
## Story
The Terraform Google provider recently [released](https://github.com/terraform-providers/terraform-provider-google/releases) a new major version (3.0.0).  This has caused errors during linting and issues with Forseti deployments.

## Proposal
Update to the new major version of the Google Provider 3.x (currently 3.4) and pin to Forseti versions to a specific version. The goal is to ensure Forseti deployments are stable regardless of new Terraform/Provider versions being released. Forseti is tested against a specific set of dependencies and we want to ensure a good user experience by not running into issues. Remove version specifications from the tests since there is no reason duplicate the versions. It is **strongly recommended** to upgrade to Terraform version 0.12.17 or greater.

Info: With Google Provider version 3.4 breaking changes were introduced between 3.3. This is an example of breaking changes being introduced within a major version, and is a good reason to lock the Forseti Terraform module into specific versions.

## Acceptance Criteria
- The Terraform integration tests pass.

**Comment by xingao267** [comment]
Hi @kevensen just wondering what's the current planned ETA for the long term fix?

**Comment by kevensen** [comment]
@xingao267 I'll be updating the resources in this module once the provider is out of beta.

https://github.com/terraform-providers/terraform-provider-google/releases

**Comment by gkowalski-google** [comment]
Attempt to update to the next major version and ensure the sub-modules are tied to a version.

**Comment by xingao267** [comment]
What's the status of making this module compatible with google provider 3.0.0?

**Comment by umairidris** [comment]
https://github.com/terraform-providers/terraform-provider-google/releases it has been GA since mid december and is causing breakages for customers. 

Can Forseti upgrade sooner in the future for breaking changes? Perhaps releasing a beta version when a new beta major version is there and then a stable release once the provider is GA. Otherwise this will be a bottleneck in using the latest stable provider release.

**Comment by xingao267** [comment]
If it's not currently planned or prioritized, I'll take a stab at upgrading it.

**Comment by gkowalski-google** [comment]
@umairidris We are looking at working on this soon. Can you elaborate on what is breaking for customers?

**Comment by xingao267** [comment]
@gkowalski-google Umair and I worked on the same team. And it's breaking for the same customer, which they needs features in google provider > 3.0.0 but Forseti module does not yet work with newer version of the provider.

@umairidris, @gkowalski-google and I synced in a different thread that their team has the capacity to take it on next week. They are going to implement this.

**Comment by chuckwilliams10** [comment]
Hi guys....so the team is looking to get TF module to work with the latest google provider version 3.0.xxx?  Any ETA as my team is in the middle of a deployment of Forseti and found out this issue. All of our TF is using the latest google provider version. ...any ETA on this....thanks a ton.

**Comment by chuckwilliams10** [comment]
@gkowalski-google --is updating Forseti with the latest Google Provider still a part of the Forseti Sprint 2020.02.17 milestone/sprint?  I am asking as our team was hoping it still was so we can deploy the TF Forseti module in our current client engagement....thanks a ton..

**Comment by gkowalski-google** [comment]
Hi @chuckwilliams10, no I'm sorry we weren't able to take it on at this time. I believe a few other people are going to look at making this change and submitting it, but I do not have an ETA. If it is not completed within the next week and a half, then I believe we will have time next sprint to help out with this.

**Comment by chuckwilliams10** [comment]
Hi @gkowalski-google---thanks..do you know who might be looking into making the change and submitting it...thanks a ton.   Also, are there any work arounds to allow the Cloud SQL instance to privately connect to the shared VPC....as the client's engagment doesn't allow any external ips for vms...in case I am missing another way to deploy the current version of the TF Forseti module..thanks a ton.

**Comment by xingao267** [comment]
Hi @chuckwilliams10, I'm taking a stab at updating the provider version this week.

**Comment by chuckwilliams10** [comment]
Hi @xingao267..awesome news....thanks a ton.
