### ISSUE TITLE
Add tests for the install_simple example

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#397]
## Story
The install_simple example is the "standard" for users to follow when installing Forseti. However there are no automated tests for it.

## Solution
Add a fixture for the install_simple example. This should be able to leverage the existing simple_example.

## Acceptance Criteria
New controls are added for the install_simple example and these tests pass.

**Comment by goofiva** [comment]
@gkowalski-google PR: https://github.com/forseti-security/terraform-google-forseti/pull/408
