### ISSUE TITLE
Ability to not provision a client VM

### ISSUE THREAD

**Issue by kyrogue** [forseti-security/terraform-google-forseti#403]
It should be possible to have the ability to not provision the client VM to reduce cost, as the single server alone is already installed with the forseti CLI tool

**Comment by gkowalski-google** [comment]
Hi @kyrogue, thanks for submitting this issue. I agree that sounds like a reasonable request, we will consider this.

**Comment by choonchernlim** [comment]
My institution is in need of this feature too.

@gkowalski-google Does CFT need help on this? The cleanest way, IMO, is to introduce a new variable: `client_enabled` (type=`boolean`, default=`true`) to control the creation of client VM. I can work on this and PR it if I have CFT's blessing to move forward.

Thanks.
