### ISSUE TITLE
Verify database flags are set

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#404]
## Story
Database flags should be verified to be configured correctly to ensure reliability for large deployments.

## Proposed Solution
Add a control to the [install_simple test](https://github.com/forseti-security/terraform-google-forseti/issues/397) to run the following command on the forseti client:
```
gcloud sql instances describe forseti-server-db-#{suffix}
```

## Acceptance Criteria
The output should contain the following text:
```
- name: net_write_timeout
    value: '240'
```

**Comment by goofiva** [comment]
-----> Verifying <install-simple-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-install-simple-local` in directory /workspace/test/fixtures/install_simple
$$$$$$ Running command `terraform output -json` in directory /workspace/test/fixtures/install_simple
server: Verifying host 10.150.0.54
Skipping profile: 'inspec-gcp' on unsupported platform: 'ubuntu/18.04'.

Profile: install_simple
Version: (not specified)
Target:  ssh://ubuntu@10.150.0.54:22

  ✔  test: Command: `gcloud sql instances describe forseti-server-db-b52a4950`
     ✔  Command: `gcloud sql instances describe forseti-server-db-b52a4950` exit_status should eq 0
     ✔  Command: `gcloud sql instances describe forseti-server-db-b52a4950` stdout should match "- name: net_write_timeout\n    value: '240'"


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 2 successful, 0 failures, 0 skipped
       Finished verifying <install-simple-local> (0m5.65s).
-----> Kitchen is finished. (0m8.08s)

**Comment by goofiva** [comment]
@gkowalski-google This test only passes on the forseti server. Client machine has permission issues.

**Comment by gkowalski-google** [comment]
> @gkowalski-google This test only passes on the forseti server. Client machine has permission issues.

OK thanks, yes that sounds good, let's just run this from the server. I think we could have done it differently from the [gcp verifier](https://github.com/forseti-security/terraform-google-forseti/blob/master/.kitchen.yml#L37) but this is fine.

**Comment by goofiva** [comment]
@gkowalski-google PR: https://github.com/forseti-security/terraform-google-forseti/pull/408
