### ISSUE TITLE
Not able to upgrade forseti "Bad request error"

### ISSUE THREAD

**Issue by jenshonkan84** [forseti-security/terraform-google-forseti#420]
Hi!

Im not able to upgrade/install forseti. I am getting this error alot:

> Error: Batch "iam-project-forseti-12cf631f modifyIamPolicy" for request "Create IAM Members roles/storage.objectViewer serviceAccount:forseti-client-gcp-92bc1acf@forseti-12cf631f.iam.gserviceaccount.com for \"project \\\"forseti-12cf631f\\\"\"" returned error: Error applying IAM policy for project "forseti-12cf631f": Error setting IAM policy for project "forseti-12cf631f": googleapi: Error 400: Policy members must be of the form "<type>:<value>"., badRequest
> 
>   on .terraform/modules/forseti/forseti-security-terraform-google-forseti-6a8c52e/modules/client_iam/main.tf line 41, in resource "google_project_iam_member" "client_roles":
>   41: resource "google_project_iam_member" "client_roles" {

Im trying with the latest 5.1.0 version.

**Comment by morgante** [comment]
It looks like you're encountering this issue in the Terraform provider: https://github.com/terraform-providers/terraform-provider-google/issues/5151

You should try pinning your Terraform provider version to 2.20.1:

```
provider "google" {
  version = "~> 2.20.1"
}
```

**Comment by gkowalski-google** [comment]
@jenshonkan84 Were you able to resolve this issue? FYI the next release of Forseti (Forseti terraform module 5.2.0) will support Google provider versions ~> 3.7.

**Comment by red2k18** [comment]
@jenshonkan84 Were you able to resolve this issue? If not, could you please try to install/upgrade to the latest Forseti version v2.25.0 (Terraform module v5.2.1) and report errors, if any?

**Comment by red2k18** [comment]
Please feel free to reopen this issue if you're still seeing this error.
