### ISSUE TITLE
Unsupported argument: An argument named "address" is not expected here

### ISSUE THREAD

**Issue by palladius** [forseti-security/terraform-google-forseti#421]
I followed (hopefully thouroughly!) the instructions in https://registry.terraform.io/modules/terraform-google-modules/forseti/google/5.1.0

1. gxcloud auth login
2. git clone --branch module-release-5.0.0 --depth 1 https://github.com/forseti-security/terraform-google-forseti.git
3. . ./helpers/setup.sh -p PROJECT_ID -o ORG_ID # existing empty org where I'm admin, existing empty project created a minutes before.
4. Using cloud shell -> TF already existing so all good

$ terraform --version
Terraform v0.12.6
+ provider.google v3.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1

Your version of Terraform is out of date! The latest version
is 0.12.18. You can update by downloading from www.terraform.io/downloads.html

Bad command:

ricc@cloudshell:~/terraform-google-forseti/riccardo (pincopallo)$ terraform apply

Error: Unsupported argument

  on .terraform/modules/forseti/forseti-security-terraform-google-forseti-1ef45bf/modules/server/main.tf line 213, in resource "google_compute_instance" "forseti-server":
 213:       address            = lookup(network_interface.value, "address", null)

An argument named "address" is not expected here.
`

**Comment by gkowalski-google** [comment]
Hi @palladius, sorry you ran into this issue. It is related to a provider update which was not being locked to a specific version in the 5.0.0 release. If you update the version of the Forseti module to 5.1.0 then this problem will be resolved. If you already have the Service Account created, then you don't need to checkout a different branch of the repository. You can just update the version within your main.tf like so:

```
module "forseti" {
      source  = "terraform-google-modules/forseti/google"
      version = "5.1.0"
```

**Comment by Arconapalus** [comment]
I came across this same issue, thank you for the update

**Comment by gkowalski-google** [comment]
@palladius Were you able to resolve this issue?

**Comment by gkowalski-google** [comment]
@palladius Closing this issue, please let me know if you need to re-open.
