### ISSUE TITLE
variable "suffix" issue impacting installation. 

### ISSUE THREAD

**Issue by thomasnyc** [forseti-security/terraform-google-forseti#423]
Hi Team,

I try to do a clean install on a new project and run into the following error:

**Code may have the issue:**

/modules/client/variables.tf - line 100
variable "suffix" {
  description = "The random suffix to append to all Forseti resources"
}

This has no default value and seems it is the reason of the following error while I ran "terraform apply" 
Any idea how to fix this? I am going to be on a customer demo quick. please help.

**Error message during "terraform apply"**

Error: Invalid template interpolation value: Cannot include the given value in a string template: string required.

Error: Error creating Firewall: googleapi: Error 404: The resource 'projects/my-project-1828-250615/global/networks/default' was not found, notFound

  on modules/client/main.tf line 137, in resource "google_compute_firewall" "forseti-client-deny-all":
 137: resource "google_compute_firewall" "forseti-client-deny-all" {

Error: Error creating Firewall: googleapi: Error 404: The resource 'projects/my-project-1828-250615/global/networks/default' was not found, notFound

  on modules/client/main.tf line 160, in resource "google_compute_firewall" "forseti-client-ssh-external":
 160: resource "google_compute_firewall" "forseti-client-ssh-external" {

Error: Error creating Firewall: googleapi: Error 404: The resource 'projects/my-project-1828-250615/global/networks/default' was not found, notFound

  on modules/server/main.tf line 119, in resource "google_compute_firewall" "forseti-server-deny-all":
 119: resource "google_compute_firewall" "forseti-server-deny-all" {

Error: Error creating Firewall: googleapi: Error 404: The resource 'projects/my-project-1828-250615/global/networks/default' was not found, notFound

  on modules/server/main.tf line 142, in resource "google_compute_firewall" "forseti-server-ssh-external":
 142: resource "google_compute_firewall" "forseti-server-ssh-external" {

Error: Error creating Firewall: googleapi: Error 404: The resource 'projects/my-project-1828-250615/global/networks/default' was not found, notFound

  on modules/server/main.tf line 176, in resource "google_compute_firewall" "forseti-server-allow-grpc":
 176: resource "google_compute_firewall" "forseti-server-allow-grpc" {

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].subnetwork': 'projects/my-project-1828-250615/regions/us-central1/subnetworks/default'. The referenced subnetwork resource cannot be found., invalid

  on modules/server/main.tf line 223, in resource "google_compute_instance" "forseti-server":
 223: resource "google_compute_instance" "forseti-server" {

**Comment by thomasnyc** [comment]
With another co-worker's help, I created a default network. Most of the Error went away except one:

Error: Invalid template interpolation value: Cannot include the given value in a string template: string required.

This has no reference on which line or part has issue. Any thoughts? 

**Full error message:**
  Enter a value: yes

null_resource.org_id_and_folder_id_are_both_empty[0]: Destroying... [id=560460426226260989]
null_resource.org_id_and_folder_id_are_both_empty[0]: Destruction complete after 0s
null_resource.org_id_and_folder_id_are_both_empty[0]: Creating...
module.server.google_compute_instance.forseti-server: Creating...
module.client.google_compute_firewall.forseti-client-deny-all: Creating...
module.server.google_compute_firewall.forseti-server-deny-all: Creating...
module.server.google_compute_firewall.forseti-server-allow-grpc: Creating...
module.client.google_compute_firewall.forseti-client-ssh-external[0]: Creating...
module.server.google_compute_firewall.forseti-server-ssh-external[0]: Creating...
module.server.google_compute_firewall.forseti-server-ssh-external[0]: Creation complete after 7s [id=forseti-server-ssh-external-52810526]
module.client.google_compute_firewall.forseti-client-ssh-external[0]: Creation complete after 7s [id=forseti-client-ssh-external-52810526]
module.client.google_compute_firewall.forseti-client-deny-all: Creation complete after 7s [id=forseti-client-deny-all-52810526]
module.server.google_compute_firewall.forseti-server-allow-grpc: Creation complete after 7s [id=forseti-server-allow-grpc-52810526]
module.server.google_compute_firewall.forseti-server-deny-all: Creation complete after 7s [id=forseti-server-deny-all-52810526]
module.server.google_compute_instance.forseti-server: Creation complete after 9s [id=forseti-server-vm-52810526]
module.client_config.data.template_file.forseti_client_config: Refreshing state...
module.client_config.google_storage_bucket_object.forseti_client_config: Creating...
module.client_config.google_storage_bucket_object.forseti_client_config: Creation complete after 0s [id=forseti-client-52810526-configs/forseti_conf_client.yaml]
module.client.google_compute_instance.forseti-client: Creating...
module.client.google_compute_instance.forseti-client: Creation complete after 9s [id=forseti-client-vm-52810526]

Error: Invalid template interpolation value: Cannot include the given value in a string template: string required.

**Comment by blueandgold** [comment]
@thomasnyc apologies for the delayed response.  Are you able to find a resolution here yet?

**Comment by thomasnyc** [comment]
I was able to find the solution. The fix is having the terraform.tfvars file like the following:

domain="xxxx.net"
org_id="xxxxxxxxxxx"
project_id="xxx.xxx.xxx"

gsuite_admin_email="someone@domain.com"

config_validator_enabled=true
config_validator_violations_should_notify=true
forseti_version="v2.18.0"

#credentials_path=""
