### ISSUE TITLE
Update non-Google Provider Versions

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#438]
## Story
To help long-term support for Forseti, update the Provider versions (except for Google which will be handled by #388) to the latest stable versions. These new versions should be specified explicitly without allowing the module to use new versions before they are tested.

## Solution
Recommend to complete this work after updating the Google provider version #388.

Ensure all providers are pinned.
Explore updating providers if the version we are currently using is far out of date.

The following providers should be updated (are there more?):
- null
- template
- random
- google-beta: This is specified by the tests, but not sure what's it's used for

## Acceptance Criteria
The automated tests use the new versions and pass.

**Comment by red2k18** [comment]
Do we want to lock down the micro version of these providers?

**Comment by red2k18** [comment]
Yes, there are more! `http`, `tls` providers can also be included to the list of providers.
