### ISSUE TITLE
[v5.0.0] tls_private_key.policy_library_sync_ssh is empty tuple

### ISSUE THREAD

**Issue by Parasdogra** [forseti-security/terraform-google-forseti#443]
Installing the Forseti using cloud shell, edited the terraform.tfvars file.

Here is the terraform version
```pdogra@cloudshell:~/terraform-google-forseti/examples/install_simple$ terraform --version
Terraform v0.12.18
+ provider.google v2.11.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1```

My result after terraform plan,

```Error: Invalid index

  on .terraform/modules/forseti-install-simple/modules/server/outputs.tf line 19, in output "forseti-server-git-public-key-openssh":
  19:   value       = tls_private_key.policy_library_sync_ssh[0].public_key_openssh
    |----------------
    | tls_private_key.policy_library_sync_ssh is empty tuple

The given key does not identify an element in this collection value.```

**Comment by nycnewman** [comment]
This is a duplicate of https://github.com/forseti-security/terraform-google-forseti/issues/361. The issue is with Terraform 12. I believe the latest release 5.1.0 fixes this.

**Comment by gkowalski-google** [comment]
Hi @Parasdogra, as @nycnewman mentions, there is an issue with 5.0.0 and Terraform versions > 0.12.6. We recommend to use the 5.1.0 version of the module instead. Please let me know if that resolves the issue.

**Comment by gkowalski-google** [comment]
I have worked with @Parasdogra and we were able to get Forseti deployed correctly.
