### ISSUE TITLE
CAI only install

### ISSUE THREAD

**Issue by umairidris** [forseti-security/terraform-google-forseti#448]
Is it possible to only install Forseti and give it the minimum permissions to access CAI and use the new policy library (e.g. all previous scanners + APIs are disabled)? If not, could we please add a new mode for the module to only enable the resources needed for CAI + policy library?

**Comment by gkowalski-google** [comment]
This is an interesting idea, thanks @umairidris. With a new input (e.g. cai_only_mode), we could:

- disable all API polling
- reduce the roles granted to server SA to those only needed for CAI data
- possibly disable all scanners other than CV (this could also be another input)
- update helper scripts to reduce roles required by the TF deployment SA (this would not be directly related to the input, instead a new parameter for the scripts)
