### ISSUE TITLE
Feature request: Add parameters for shielded VM properties

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#456]
Currently, the module allows me to change the boot images through `client_boot_image` and `server_boot_image`.

I have tested it with shielded VM (`gce-uefi-images/ubuntu-1804-lts`) and it works without any problems.

That said, would it be possible to add a few parameters to enable several shielded VM properties (ex: secure boot, vtpm, integrity monitoring)?

Currently, it be can done by modifying the following codebase to satisfy this need, but I prefer not to do this every time I upgrade this module:-

```
// modules/server
resource "google_compute_instance" "forseti-server" {
  ...

  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }

  ...
}

// modules/client
resource "google_compute_instance" "forseti-client" {
  ...

  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }

  ...
}
```

Thank you for your consideration.

**Comment by red2k18** [comment]
Thanks for your interest! We will review this request in our next meeting and will provide an update here. Wanted to check if you are interested in contributing this feature.

**Comment by choonchernlim** [comment]
I'm willing to help, but I could use some direction on how you guys want to proceed with this depending on how customizable we want it to be.

Given all shielded VMs belong to `gce-uefi-images` image project, one way is to parse the image path to determine whether the image is a shielded VM or not before adding that `shielded_instance_config` block with that 3 properties set to `true`.

Another way is to introduce 2 more optional variables with default value of either `{}` or `null` to this Forseti module: `client_shielded_instance_config` and `server_shielded_instance_config`. Then, user can provide their own config if they use shielded VMs. 

If your team can provide some directions here, I can work with @xingao267  to make this happen.
