### ISSUE TITLE
Unable to deploy GKE End to End example

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/terraform-google-forseti#458]
### Story

Customer is unable to deploy the [GKE End to End example](https://github.com/forseti-security/terraform-google-forseti/blob/master/examples/on_gke_end_to_end/main.tf) due to IAM Policy error and other errors. Followed the instructions on the Forseti website [here](https://forsetisecurity.org/docs/latest/setup/forseti-on-gke.html) for new GKE cluster, including:
1. In GCP console, cloned the repo
2. Created main.tf in a new folder - added project ID, ORG ID, Region, email etc in this .tf
3. Ran helper script to create service accounts
4. Initialised and applied my main.tf 

but ran into errors such as:

```
Error: Error applying IAM policy for service account 'projects/project-xx/serviceAccounts/forseti-server-gcp-123123123@project-xx.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/project-xx/serviceAccounts/forseti-server-gcp-123123123@project-xx.iam.gserviceaccount.com': googleapi: Error 400: Identity namespace does not exist (project-xx.svc.id.goog)., badRequest
  on ../modules/on_gke/main.tf line 122, in resource “google_service_account_iam_binding” “forseti_server_workload_identity”:
 122: resource “google_service_account_iam_binding” “forseti_server_workload_identity” {
Error: Error applying IAM policy for service account 'projects/project-xx/serviceAccounts/forseti-client-gcp-123123123@project-xx.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/project-xx/serviceAccounts/forseti-client-gcp-123123123@project-xx.iam.gserviceaccount.com': googleapi: Error 400: Identity namespace does not exist (project-xx.svc.id.goog)., badRequest
  on ../modules/on_gke/main.tf line 131, in resource “google_service_account_iam_binding” “forseti_client_workload_identity”:
 131: resource “google_service_account_iam_binding” “forseti_client_workload_identity” {
Error: googleapi: Error 400: Master version “1.13.11-gke.5” is unsupported., badRequest
  on .terraform/modules/forseti-on-gke.gke/modules/beta-public-cluster/cluster.tf line 22, in resource “google_container_cluster” “primary”:
  22: resource “google_container_cluster” “primary” {
Error: googleapi: Error 400: Master version “1.13.11-gke.5” is unsupported., badRequest
  on .terraform/modules/forseti-on-gke.gke/modules/beta-public-cluster/cluster.tf line 22, in resource “google_container_cluster” “primary”:
  22: resource “google_container_cluster” “primary” {

```
### Solution

Customer was able to deploy GKE application by completing the following:

1. Ensure the following roles are assigned to your service account that is deploying Forseti (i.e. this would be your cloud-foundation-xx service account that you created in the helper script):

- Kubernetes Engine Cluster Admin (roles/container.clusterAdmin)
- Kubernetes Engine Developer (roles/container.developer)
- Project IAM Admin (roles/resourcemanager.projectIamAdmin)

2. Ensure that the following APIs are enabled:

- Kubernetes Engine API - container.googleapis.com
- Compute Engine API - compute.googleapis.com

3. `export GOOGLE_APPLICATION_CREDENTIALS="/path/to/credentials.json"`

4.  In terraform-google-forseti/examples/on_gke_end_to_end/main.tf, change the following variables:
https://github.com/forseti-security/terraform-google-forseti/blob/30d84f0de9752ba2ba89649651e13ceaee6faf4f/examples/on_gke_end_to_end/main.tf#L27:
Change:
```
provider "google-beta" { 
   version = "~>2.12.0"
   project = var.project_id
}
```
to:
```
provider "google-beta" { 
   version = "~>2.18.0"
   project = var.project_id
}
```
https://github.com/forseti-security/terraform-google-forseti/blob/30d84f0de9752ba2ba89649651e13ceaee6faf4f/examples/on_gke_end_to_end/main.tf#L103
Change:
```
module "gke" {
   version = "5.0.0"
}
```
to:
```
module "gke" {
   version = "6.2.0"
}
```

https://github.com/forseti-security/terraform-google-forseti/blob/b68706b9b4470fde95aa59aafafd0c01a6469910/examples/on_gke_end_to_end/variables.tf#L137-L141
Change:
```
variable "kubernetes_version" {
  type        = string
  description = "The Kubernetes version of the masters. If set to 'latest' it will pull latest available version in the selected region."
  default     = "1.13.12-gke.8"
}
```
to:
```
variable "kubernetes_version" {
  type        = string
  description = "The Kubernetes version of the masters. If set to 'latest' it will pull latest available version in the selected region."
  default     = "1.15.7-gke.2"
}
```

Error was found after applying the above:

```
Error: Error waiting for creating GKE NodePool:
        (1) Not all instances running in IGM after 21.993710723s. Expect 1. Current errors: [CONDITION_NOT_MET]: Instance ‘gke-forseti-cluster-default-node-pool-123-123’ creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 954082350089. Add instance projects/project-xx/zones/australia-southeast1-b/instances/gke-forseti-cluster-default-node-pool-123-123 to the constraint to use external IP with it
        (2) Not all instances running in IGM after 27.090571024s. Expect 1. Current errors: [CONDITION_NOT_MET]: Instance ‘gke-forseti-cluster-default-node-pool-9dc017b0-6ltb’ creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 954082350089. Add instance projects/project-xx/zones/australia-southeast1-a/instances/gke-forseti-cluster-default-node-pool-9dc017b0-6ltb to the constraint to use external IP with it
        (3) Not all instances running in IGM after 27.530488118s. Expect 1. Current errors: [CONDITION_NOT_MET]: Instance ‘gke-forseti-cluster-default-node-pool-380e5d02-jpzl’ creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project 954082350089. Add instance projects/project-xx/zones/australia-southeast1-c/instances/gke-forseti-cluster-default-node-pool-380e5d02-jpzl to the constraint to use external IP with it.
  on .terraform/modules/forseti-on-gke.gke/modules/beta-public-cluster/cluster.tf line 212, in resource “google_container_node_pool” “pools”:
 212: resource “google_container_node_pool” “pools” {
```

From customer: `Which I think is a restriction on the project level from the G Suite admin, that disallows external IPs…` --> customer enabled external IPs and issue went away.

### Acceptance Criteria

Forseti on GKE end to end example deploys successfully.

**Comment by blueandgold** [comment]
Assigning to @gkowalski-google who will take a look at this as part of the 2.25 release. Another user reported this issue on slack that he was unable to deploy the GKE version by following the website instruction.
