### ISSUE TITLE
`manage_rules_enabled=false` prevents Forseti service from starting

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#501]
**PROBLEM**

Related to #468...

When setting `manage_rules_enabled` to `false`, the `rules/` dir is not created in the `forseti-server-xxxx` GCS bucket. 

This prevents Forseti service from starting up successfully in server VM:-

```
$ sudo systemctl status forseti
Unit forseti.service could not be found.
$ sudo systemctl restart forseti
Failed to restart forseti.service: Unit forseti.service not found
```

Here's the error from "Serial port 1 (console)" log:- 

```
INFO startup-script: CommandException: No URLs matched: gs://forseti-server-13188a0b/rules
INFO startup-script: Return code 1.
INFO Finished running startup scripts.
```

**PROPOSED SOLUTION**

Ensure `rules/` dir is created in [modules/rules/main.tf](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/rules/main.tf) by adding this code block:-

```
// Creates an empty dir to ensure Forseti service starts if `manage_rules_enabled` is set to false.
resource "google_storage_bucket_object" "empty_rules_dir" {
  count   = var.manage_rules_enabled == false ? 1: 0
  name    = "rules/"
  content = "n/a"
  bucket  = var.server_gcs_module.forseti-server-storage-bucket

  lifecycle {
    ignore_changes = [
      content,
      detect_md5hash,
    ]
  }
}
```

Now, the Forseti service starts successfully in server VM:-

```
$ sudo systemctl status forseti
● forseti.service - Forseti API Server
   Loaded: loaded (/lib/systemd/system/forseti.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-02-10 16:01:35 UTC; 3min 57s ago
 Main PID: 4084 (forseti_server)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/forseti.service
           └─4084 /usr/bin/python3 /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql+pymysql:/
Feb 10 16:01:35 forseti-server-vm-13188a0b systemd[1]: Started Forseti API Server.
```

I don't mind creating a PR bug fix for this if you are okay with it. Thank you.

**Comment by red2k18** [comment]
@choonchernlim Thanks for reporting the issue and proposing the solution. Would you be so kind to submit a PR for this?

**Comment by choonchernlim** [comment]
@red2k18 I'll do that.

By the way, do we want both `rules/` and `policy-library/` empty dirs created?

Right now, if config validator is also enabled, we will get this message, but it won't cause Forseti from starting up:-
```
  Feb 18 14:41:05 forseti-server-vm-09f31070 startup-script: INFO startup-script: CommandException: No URLs matched: gs://forseti-server-09f31070/policy-library
  Feb 18 14:41:05 forseti-server-vm-09f31070 startup-script: INFO startup-script: No policy available, continuing with Forseti installation
```

Do you want just `rules/` empty dir created? Thanks.

**Comment by red2k18** [comment]
@choonchernlim Thanks for being willing to contribute.

Let's address the issue that is preventing Forseti service from starting in this PR i.e the missing `rules/`. I really appreciate you checking on this.

**Comment by choonchernlim** [comment]
Sounds good. I'll add just `rule/` empty dir for now. Will PR in the coming days.

**Comment by gkowalski-google** [comment]
Thanks @choonchernlim! While adding an empty dir will stop the error from happening in the startup script, if users set manage_rules_enabled to false and do not provide any rules (and they aren't intending to only use Config Validator), then nothing will be scanned for. This might create some confusion and a false sense of security. I understand the use case though. Can you also add in some logging (probably in the startup script?) that will alert users that no rules were found and the Forseti scanners will not be functional?

**Comment by choonchernlim** [comment]
@gkowalski-google  Yes, I can try adding some logging in the startup script to reflect that.

By the way, I think there are 2 ways to fix this error. 

One is to introduce an empty `rules/` dir, like what I suggested above.

Another is to **only execute** `gsutil cp -r gs://${storage_bucket_name}/rules ${forseti_home}/` if `rules/` dir exists in the startup script. I'm not sure if that will truly fix the problem until I try it, but if that works, I think that will give us cleaner and more consistent implementation if both rules and config validator are disabled (ie: we are not going to have one empty `rules/` and missing `policy-library/`).

What do you guys think?

**Comment by gkowalski-google** [comment]
I think my preference is on the former, to create an empty rules dir. The reason is that if a user chooses to manage their rules, then how will they get them to the server? Leaving the GCS "sync" option means they can copy their custom rules to the GCS bucket. Otherwise they will need to copy them to the server using SCP or something.

Can you elaborate some on what is the intended use case?

**Comment by choonchernlim** [comment]
For my institution, we are separating Forseti provisioning and rules/policies management into 2 steps. 

As part of the IaC team, I'm responsible in provisioning Forseti with `manage_rules_enabled=false` and `config_validator_enabled=true`. This will create a GCS bucket with no rules and policies, but the server VM will be running and it will be connected to CSCC.

Then, there is a security team who is responsible in managing these rules and policy library (we are enabling both for now). Their rules/policies are stored in separate locked down Git repo, which will be pushed to the GCS bucket through some CI/CD pipeline.

So, we have these separation of concerns between these 2 teams.  My job is to ensure I can provision the server VM successfully so that the security team can create and deploy the rules/policies later.

Does this help? Thank you.
