### ISSUE TITLE
Access denied to cloud sql from startup-script on forseti server.

### ISSUE THREAD

**Issue by shazzzzam** [forseti-security/terraform-google-forseti#509]
Terraform-google-forseti version 5.1.2
Terraform version "v2.24.1"

The forseti server fails during the startup script when running:
`python3 $USER_HOME/forseti-security/install/gcp/upgrade_tools/db_migrator.py`

Error message:
```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'cloudsqlproxy~10.64.56.34' (using password: NO)") (Background on this error at: http://sqlalche.me/e/e3q8)
```

I'm using `cloudsql_private = true`

**Comment by red2k18** [comment]
@shazzzzam Are you still experiencing this issue? I just deployed Forseti with the same configuration and startup script completed successfully.

**Comment by red2k18** [comment]
Please feel free to reopen the issue if you are experiencing any issues.
