### ISSUE TITLE
The purpose of `ping` in the startup script?

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#510]
Given that my institution requires all VM egress communications to be blocked by default, I'm trying to figure out what egress firewall rules (with higher priority number) are needed for the Forseti installation to be successful and make some justifications for them. 

What's the primary reason for this `ping` test in the startup script?

```
...

INTERNET_CONNECTION="$(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline)"

# Log status of internet connection
if [ $INTERNET_CONNECTION == "offline" ]; then
  echo "Forseti Startup - A connection to the internet was not detected."
fi

...

# Install Forseti Security.
cd $USER_HOME
if [ $INTERNET_CONNECTION == "online" ]; then
  rm -rf *forseti*
fi

...
```

It seems like even if the ping fails against `google.com`, it will still proceed to query other web links (ex `github.com`, `download.docker.com`, etc). 

Thank you.

**Comment by gkowalski-google** [comment]
Hi @choonchernlim, that was recently added for the GCE deployment so that users can deploy Forseti privately(with Cloud NAT) and allow for Forseti to get fully installed (e.g. Ubuntu patches, Forseti dependencies, Forseti itself, etc.), and then remove the NAT so Forseti had not outside access. Previously when people did this Forseti would always get deleted on Startup, but if the VM did not have external access then Forseti would not get re-installed. Does that help?

**Comment by choonchernlim** [comment]
Does Forseti need outside communications **only for** completing the installation on VM startup?

Given our VM blocks all egress communications by default, I had to open TCP 22, 80, 443 and ICMP for the installation to be successful.

My security team analyzed the VPC flow log and I was told they are seeing outside communications even after the installation has completed on VM startup. I can't confirm or deny the accuracy of this statement as I haven't spend too much debugging this myself.

Your suggestion about removing NAT after installation on VM startup intrigues me, but is there any implication doing so?
 
CC'd @xingao267 for awareness.

**Comment by gkowalski-google** [comment]
I don't believe it's documented anywhere what are all the external sources are, but assuming you are using a VPC then it should be able to access all of the private Google APIs. However, there are other known external sources:

- Blacklist scanner (if enabled)
- Notifier: depending on which options are enabled, then it will need external access. For example, if you want Forseti to notify violations via email then it will need external access.

In the cases I have heard about where people removed the Cloud NAT, they were only interested in tracking the violations in the database along with GCS. So they did not need external access for the other notifiers to work.

**Comment by choonchernlim** [comment]
Looking at the generated `forseti_conf_server.yaml`, I see the following scanners enabled:-

- bigquery
- blacklist (_identified as an external resource_)
- bucket_acl
- config_validator
- cloudsql_acl
- firewall_rule
- group
- groups_settings
- iam_policy
- iap
- instance_network_interface
- ke_version_scanner
- kms_scanner
- location
- log_sink
- resource
- service_account_key

Given the above list, is "blacklist" the only scanner that is an external resource? Is there a documentation where I can pass it to my security team?

Regarding notifier, besides writing violations and inventory to GCS, it also reports violations to CSCC. There are no Slack or email notifications. That said, is it accurate to say my notifiers wouldn't need any egress communications?

I'm trying to figure out what activities are flooding the VPC flow log with egress communications.

Thank you.

**Comment by gkowalski-google** [comment]
I believe that is correct about the blacklist scanner; the other scanners rely on data collected by Google APIs. GCS and CSCC should not need egress either.

**Comment by choonchernlim** [comment]
Thank you for the info. For now, I can get it working by disabling ICMP.
