### ISSUE TITLE
Can't connect to MySQL server on '127.0.0.1'

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#514]
@gkowalski-google , I'm currently experimenting blocking egress FW rules to see if I'm able to disable EGRESS after a successful Forseti installation on VM startup instead of removing NAT.

First, because my VPC has all EGRESS blocked by default (`0.0.0.0/0, egress, deny, all`), I have this FW rule (`0.0.0.0/0, egress, allow, tcp 22,80,443 and icmp`), which allows Forseti to install properly on VM startup.

Then, I removed that FW rule and restarted the VM (not reset). In theory, without ICMP, the startup script will think there's no internet connection and should halt at some point without messing with the installed Forseti security.

When I look at the Serial Port 1 log, I'm seeing a lot of this error from the Forseti service:-
```
Feb 21 18:08:19 forseti-server-vm-e6fbeec4 forseti_server[5352]:   File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 325, in __init__
Feb 21 18:08:19 forseti-server-vm-e6fbeec4 forseti_server[5352]:     self.connect()
Feb 21 18:08:19 forseti-server-vm-e6fbeec4 forseti_server[5352]:   File "/home/ubuntu/forseti-security/.eggs/PyMySQL-0.9.3-py3.6.egg/pymysql/connections.py", line 630, in connect
Feb 21 18:08:19 forseti-server-vm-e6fbeec4 forseti_server[5352]:     raise exc
Feb 21 18:08:19 forseti-server-vm-e6fbeec4 forseti_server[5352]: pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")
```

... and the Forseti service died.

I believe that loopback address is hardcoded at https://github.com/forseti-security/forseti-security/blob/v2.24.1/install/gcp/scripts/initialize_forseti_services.sh#L35 .

How do I go about debugging this problem? 

Why is it trying to connect to the loopback address instead of the CloudSQL IP?

Thank you.

**Comment by gkowalski-google** [comment]
Hi @choonchernlim, Forseti is using Cloud SQL proxy to connect to the Cloud SQL instance. The proxy is running locally as a service. Is the proxy service running? `sudo systemctl status cloudsqlproxy`. Is the deny all FW rule blocking the access to the loopback address?

**Comment by choonchernlim** [comment]
In theory, when the VM restarts, it should restart all necessary services itself even after I block TCP 22,80,443 and ICMP.

Here's the current FW rules:- 

![Screen Shot 2020-02-21 at 12 53 51 PM](https://user-images.githubusercontent.com/6835135/75063031-99841d80-54a9-11ea-8664-04b00a69b03a.png)

Given these rules, I don't think it should block loopback address from server VM.

Can you verify?

Thank you.

**Comment by choonchernlim** [comment]
@gkowalski-google  `cloudsqlproxy` ran but `forseti` failed.

```
$ sudo systemctl status cloudsqlproxy
● cloudsqlproxy.service - Cloud SQL Proxy
   Loaded: loaded (/lib/systemd/system/cloudsqlproxy.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-02-21 20:52:07 UTC; 29s ago
 Main PID: 4138 (cloud_sql_proxy)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/cloudsqlproxy.service
           └─4138 /usr/local/bin/cloud_sql_proxy -instances=ado-forseti-5-1-2:us-central1:forseti-server-db-e6fbeec4=tcp:3306
Feb 21 20:52:07 forseti-server-vm-e6fbeec4 systemd[1]: Started Cloud SQL Proxy.
Feb 21 20:52:07 forseti-server-vm-e6fbeec4 cloud_sql_proxy[4138]: 2020/02/21 20:52:07 Rlimits for file descriptors set to {&{8500 8500}}

$ sudo systemctl status forseti
● forseti.service - Forseti API Server
   Loaded: loaded (/lib/systemd/system/forseti.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-02-21 20:53:13 UTC; 1s ago
  Process: 4931 ExecStart=/usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql+pymysql://root@127.0.0.1:3306/forseti_sec
 Main PID: 4931 (code=exited, status=1/FAILURE)
```

**Comment by choonchernlim** [comment]
@gkowalski-google This is due to my lack of familiarity with Cloud SQL proxy (sorry), but does it require `0.0.0.0/0, egress, allow, tcp 443` for it to work? After a successful installation, I started blocking each port (22, 80 and 443) and I found out that TCP 443 is needed for Forseti service to run properly on VM restart. Thank you.

**Comment by gkowalski-google** [comment]
@choonchernlim I can look into this next week after I get the patches released.

**Comment by choonchernlim** [comment]
@gkowalski-google I received confirmations from other Googlers that `tcp 443` is needed by Cloud SQL for it to work. I'm going to go ahead and close this. Thank you.

**Comment by gkowalski-google** [comment]
Awesome, thanks for digging into that, glad you got it resolved!

**Comment by choonchernlim** [comment]
We are looking into ways to limit this Cloud SQL egress traffic to prevent possible data exfiltration, and assuming the option is viable and can be cleanly done, I'll consider upstreaming it to CFT.
