### ISSUE TITLE
Client Firewall rule difference with original Forseti

### ISSUE THREAD

**Issue by mitsuo0114** [forseti-security/terraform-google-forseti#52]
Hi, I have found firewall difference between this terraform installation and original forseti source.
Original source have firewall rules which are named "forset-client-allow-ssh-external" and "forseti-client-deny-all". But this terraform plugin doesn't have.

https://github.com/terraform-google-modules/terraform-google-forseti/blob/master/modules/client/main.tf

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/install/gcp/installer/forseti_client_installer.py

It this intentional?

**Comment by adrienthebo** [comment]
The absence of these firewall rules was a bug; we've added those rules to the Forseti client module today: https://github.com/terraform-google-modules/terraform-google-forseti/blob/master/modules/client/main.tf#L107-L147

Could you try out the latest revision of this code and see if it addresses your concern?

**Comment by mitsuo0114** [comment]
Thanks, understood!
sorry I cannot take time to try it now but let me find..

by the way, sorry to have not good word "intentional", I don't have any intention to blame anything but just confirm any background.

Thanks and Regards,

**Comment by aaron-lane** [comment]
@mitsuo0114 has your issue been resolved?

**Comment by mitsuo0114** [comment]
@aaron-lane  Really sorry for my delay.
I could confirmed the firewall rules are appeneded with latest version "1.4.2".

Log : 
> module.forseti.module.client.google_project_iam_member.client_roles[0]: Creation complete after 10s (ID: forsetiinstall-sample/roles/storage.obj...install-sample.iam.gserviceaccount.com)
> module.forseti.module.client.google_compute_firewall.forseti-client-ssh-external: Creation complete after 11s (ID: forseti-client-ssh-external-de9c21c8)
> module.forseti.module.client.google_compute_firewall.forseti-client-deny-all: Creation complete after 14s (ID: forseti-client-deny-all-de9c21c8)
> module.forseti.server.google_sql_database_instance.master: Still creating... (20s elapsed)


Thank you!
