### ISSUE TITLE
Unable to deploy using GKE end-to-end example as module

### ISSUE THREAD

**Issue by rux616** [forseti-security/terraform-google-forseti#527]
### Story
As per the [Forseti docs for deploying on GKE](https://forsetisecurity.org/docs/latest/setup/forseti-on-gke.html), I attempted to use the GKE end-to-end example as a module but ran into the following errors:
```
Error: Failed to initialize config: invalid configuration: no configuration has been provided

  on .terraform/modules/forseti_on_gke.gke/terraform-google-modules-terraform-google-kubernetes-engine-f99ddf4/modules/beta-public-cluster/auth.tf line 29, in provider "kubernetes":
  29: provider "kubernetes" {



Error: Failed to initialize config: invalid configuration: no configuration has been provided

  on .terraform/modules/forseti_on_gke/forseti-security-terraform-google-forseti-8e1efcb/examples/on_gke_end_to_end/main.tf line 37, in provider "kubernetes":
  37: provider "kubernetes" {`
```

While troubleshooting this, my colleague and I noticed something interesting, specifically, that the version constraints weren't being honored. Functionally, this meant that the kubernetes provider was at 1.11.0, thus inducing the above bug, and could be fixed by changing my `providers.tf` and manually pinning the kubernetes provider at 1.10.0 instead:

```hcl
provider "kubernetes" {
  version = "~> 1.10.0"
}
```

Contents of `main.tf` when using end-to-end example as module (variable values stored in `terraform.tfvars`):
```hcl
module "forseti_on_gke" {
  source  = "terraform-google-modules/forseti/google//examples/on_gke_end_to_end"
  version = "~> 5.1.2"

  domain                        = var.domain
  git_sync_private_ssh_key_file = var.git_sync_private_ssh_key_file
  gsuite_admin_email            = var.gsuite_admin_email
  org_id                        = var.org_id
  project_id                    = var.project_id
}
```

### Various outputs
Output of `terraform-0.12.21 providers` when using end-to-end example as module:
```
.
├── provider.google
└── module.forseti_on_gke
    ├── provider.google ~> 2.12.0
    ├── provider.google-beta ~> 2.12.0
    ├── provider.helm.forseti
    ├── provider.kubernetes.forseti
    ├── module.forseti
    │   ├── provider.google ~> 2.12
    │   ├── provider.helm ~> 0.10
    │   ├── provider.http
    │   ├── provider.kubernetes
    │   ├── provider.local
    │   ├── provider.null
    │   ├── provider.random
    │   ├── provider.tls
    │   ├── module.client
    │   │   ├── provider.google ~> 2.11
    │   │   ├── provider.null
    │   │   └── provider.template
    │   ├── module.client_config
    │   │   ├── provider.google (inherited)
    │   │   └── provider.template
    │   ├── module.client_gcs
    │   │   ├── provider.google (inherited)
    │   │   └── provider.null
    │   ├── module.client_iam
    │   │   └── provider.google (inherited)
    │   ├── module.cloudsql
    │   │   ├── provider.google (inherited)
    │   │   └── provider.null
    │   ├── module.server_config
    │   │   ├── provider.google (inherited)
    │   │   ├── provider.null
    │   │   └── provider.template
    │   ├── module.server_gcs
    │   │   ├── provider.google (inherited)
    │   │   └── provider.null
    │   ├── module.server_iam
    │   │   └── provider.google (inherited)
    │   └── module.server_rules
    │       ├── provider.google (inherited)
    │       └── provider.template
    ├── module.gke
    │   ├── provider.google (inherited)
    │   ├── provider.google-beta (inherited)
    │   ├── provider.kubernetes
    │   ├── provider.null
    │   └── provider.random
    └── module.vpc
        ├── provider.google (inherited)
        └── provider.null
```

Output of `terraform-0.12.21 providers` when using end-to-end example directly:
```
.
├── provider.google ~> 3.7.0
├── provider.google-beta ~> 3.7.0
├── provider.helm ~> 0.10.4
├── provider.helm.forseti
├── provider.http ~> 1.1.0
├── provider.kubernetes ~> 1.10.0
├── provider.kubernetes.forseti
├── provider.local ~> 1.4.0
├── provider.tls ~> 2.1.1
├── module.forseti
│   ├── provider.google ~> 3.7
│   ├── provider.google-beta ~> 3.7
│   ├── provider.helm ~> 0.10
│   ├── provider.http
│   ├── provider.kubernetes ~> 1.10
│   ├── provider.local
│   ├── provider.null ~> 2.0
│   ├── provider.random ~> 2.0
│   ├── provider.template ~> 2.0
│   ├── provider.tls ~> 2.1
│   ├── module.client
│   │   ├── provider.google ~> 3.7
│   │   ├── provider.null
│   │   └── provider.template
│   ├── module.client_config
│   │   ├── provider.google
│   │   └── provider.template
│   ├── module.client_gcs
│   │   ├── provider.google
│   │   └── provider.null
│   ├── module.client_iam
│   │   └── provider.google
│   ├── module.cloudsql
│   │   ├── provider.google
│   │   ├── provider.null
│   │   └── provider.random
│   ├── module.server_config
│   │   ├── provider.google
│   │   ├── provider.null
│   │   └── provider.template
│   ├── module.server_gcs
│   │   ├── provider.google
│   │   └── provider.null
│   ├── module.server_iam
│   │   └── provider.google
│   └── module.server_rules
│       ├── provider.google
│       └── provider.template
├── module.gke
│   ├── provider.google
│   ├── provider.google-beta >= 3.1, <4.0.0
│   ├── provider.kubernetes ~> 1.10.0
│   ├── provider.null
│   └── provider.random
└── module.vpc
    ├── provider.google <4.0,>= 2.12
    ├── module.routes
        ├── provider.google <4.0,>= 2.12
        └── provider.null
    ├── module.subnets
        └── provider.google <4.0,>= 2.12
    └── module.vpc
        └── provider.google <4.0,>= 2.12
```

Output of `terraform-0.12.21 version` when using end-to-end example as module:
```
Terraform v0.12.21
+ provider.google v2.12.0
+ provider.google-beta v2.12.0
+ provider.helm v0.10.4
+ provider.http v1.1.1
+ provider.kubernetes v1.11.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

Output of `terraform-0.12.21 version` when using end-to-end example directly:
```
Terraform v0.12.21
+ provider.google v3.7.0
+ provider.google-beta v3.7.0
+ provider.helm v0.10.4
+ provider.http v1.1.1
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

**Comment by gkowalski-google** [comment]
Hi @rux616, thanks for submitting this issue. We are still in the process of updating the GKE modules, example and documentation. I have recently updated the [GKE end-to-end example](https://github.com/forseti-security/terraform-google-forseti/tree/master/examples/on_gke_end_to_end) to use more recent versions of the core providers (e.g. Google/Helm/Kubernetes providers, and newer versions of the core module dependencies (e.g. GCP Network and GKE).

We are working towards releasing Forseti v2.25 which will have this all resolved, but right now the GKE examples are not yet complete. The main thing that needs to be finished is for us to publish a new Helm Chart, and for us to complete release testing of Forseti v2.25.

While the documentation on the website says you can source the example directly, I don't think this is a good idea (I will be updating soon). It's better to copy the contents of this example into a local directory, and supply the required variables to it with a terraform.tfvars file. There are a few big benefits of this:

- lock down your deployment of Forseti to changes that you control
- if you need to utilize any of the many other Terraform variables, these cannot be supplied to the example without the example being updated to support them.

Unfortunately I think it is best to wait for the Forseti v2.25 release to use Forseti on GKE. I'm hoping this will be done in the next week or two. Please let me know if you have any questions.

**Comment by gkowalski-google** [comment]
Hi @rux616, Forseti v2.25.0 was released last week including some changes for the Forseti on GKE examples. There is a [bug in Helm 2](https://github.com/helm/helm/issues/6361) which might pop up during your initial terraform apply; re-running Terraform apply should work. There is an issue to [upgrade to Helm 3](https://github.com/forseti-security/terraform-google-forseti/issues/548), but no ETA on when that might be delivered.
