### ISSUE TITLE
No firewall rules for egress traffic

### ISSUE THREAD

**Issue by gingersnapz** [forseti-security/terraform-google-forseti#528]
All egress traffic in GCP is allowed implicitly. Best practice typically requires a default deny egress firewall rule that would catch any unauthorized traffic leaving the compute resource. There currently is only a default deny rule for ingress traffic.

**Comment by gkowalski-google** [comment]
Thanks for submitting the issue @gingersnapz. There has been some work recently to capture the various egress sources of traffic from the Forseti server VM. This might not be a complete list, but hope it helps. Thanks to @xingao267 for this work!

There has been some talk to provide an example in the Terraform repo that would make Forseti private by default and have some of these other best practices incorporated into it. We are definitely open to community contributions for this effort.

----------

**Startup phase**

1. A bunch of apt-get, wget as in the startup script. The target ips include but not limited to 
  - packages.cloud.google.com:80 (172.217.214.139)
  - security.ubuntu.com:80 (91.189.91.23)
  - gce.archive.ubuntu.com:80 (35.184.34.241)
  - archive.canonical.com:80 (91.189.92.150)
  - ...This can be both Google IPs or non-Google IPs
2. Setting up Cloud SQL proxy and attempts several IPs as far as I can tell, which includes but not limited to:
  - 74.125.129.95
  - 74.125.69.95
  - 108.177.111.95
  - 74.125.126.95
  - ... (Note these are all Google owned IPs.) I could find a place where it says this is a complete list of IPs that cloudsql proxy service will use
3. Connecting to the sql database, this one is easy. But currently not included in the forseti module, but I can upstream a PR to add it.
  - The rule would look like something like Egress; IP ranges: <the sql internal IP known after sql created>; 3306, 3307; Allow; <some priority>

**Ongoing Forseti scanning jobs**
1. Connecting to Cloud SQL proxy and attempts several IPs same as above.
2. Connecting to the sql database, same as above.
3. (If we only enable config validator scanner and not use legacy scanners) Cloud Asset Inventory API calls to various Google IPs to fetch metadata of resources.

**Other**
1. I also see connections to 127.0.0.1 through port 3306, which seems a local connection used by cloud sql proxy, so i guess we don't need to have a firewall rule to deal with that? Please correct me if I am wrong. _Update_: I think you do actually need a rule for this.
2. Depending on if you leverage Forseti notifier to emails or slack notifications, you will need to account for that traffic as well.

**Comment by xingao267** [comment]
@gingersnapz we have this use case as well where we put a default deny-all egress rule for any IP and protocols. We are planning to upstream an example to illustrate how to set that up with additional firewall rules, private zone, DNS record and Routes.

@gkowalski-google for the going scanning job, there is one more egress traffic which is CSCC notification if enabled.

**Comment by gkowalski-google** [comment]
Thanks, updated to include the Blacklist scanner, and CSCC/GCS notifier options.

**Comment by gkowalski-google** [comment]
@gingersnapz There is some work going on to provide an example of a fully private deployment. This will add an option to block public egress.
