### ISSUE TITLE
Nested `policy-library` dir in server VM

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#554]
We are seeing several nested `policy-library` dir created under `/ubuntu/home` in the server VM... I think this maybe the root cause of the problem...

From Forseti module, the policy library home is set to `$USER_HOME/policy-library`.
https://github.com/forseti-security/terraform-google-forseti/blob/master/variables.tf#L534-L537
```
variable "policy_library_home" {
  description = "The local policy library directory."
  default     = "$USER_HOME/policy-library"
}
```

This value is made available to VM startup script as `POLICY_LIBRARY_HOME` env.
https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/templates/scripts/forseti-server/forseti_environment.sh.tpl#L3
```
export POLICY_LIBRARY_HOME=${policy_library_home}
```

This script from Forseti-Security appends yet another `policy-library` to `$USER_HOME/policy-library`.
https://github.com/forseti-security/forseti-security/blob/ddc068c3cfe5d663fd70d400acfd692efa641399/install/gcp/scripts/initialize_forseti_services.sh#L43
```
CONFIG_VALIDATOR_COMMAND+=" --policyPath='${POLICY_LIBRARY_HOME}/policy-library/policies'"
```

Right now, we are seeing 3 nested dirs (`../policy-library/policy-library/policy-library`) in the VM.

Can you verify that this is working as intended?

Thank you.

**Comment by gkowalski-google** [comment]
Hi @choonchernlim. It is expected that there are only 2 `policy-library` dirs. The policy library home defaults to /home/ubuntu/policy-library. The reason that there is another policy-library dir is that the home dir is where the policy-library gets cloned into, which creates the 2nd policy-library dir. Then under that, we have the main content. 

I just re-ran terraform apply using master branch and everything seems right to me. I have done testing with the latest release as well and this is working.

Directory structure:

- /home/ubuntu/policy-library: Home
  - policy-library/: Cloned repo
    - policies/templates/: Templates
    - policies/constraints/: Your constraints
    - lib/: Library files shared by templates

I'm not sure how you ended up with 3 policy-library dirs. Can you provide some of the details from your main.tf?

**Comment by choonchernlim** [comment]
Per @xingao267 , his gut feel is I ran the initial provisioning with `config_validator_enabled=true` and since GCS doesn't have `policy-library` dir yet, it fails and causes some inconsistent state. Xin, please correct me if I'm wrong.

So, we talked about running the initial provisioning with `config_validator_enabled=false`, copy the policies into GCS and reprovision with `config_validator_enabled=true`... OR...

Create empty `policy-library/lib` dir and `policy-library/policies` dir to see if it satisfies the startup script, then populate the policies later (by security team). 

My question to you is did you provisioning with `config_validator_enabled=true` too?

**Comment by gkowalski-google** [comment]
I typically deploy using the git-sync feature for the policy library:
```
config_validator_enabled      = true
policy_library_sync_enabled = true
policy_library_repository_url  = {URL_TO_GREGGS_PRIVATE_POLICY_LIBRARY_REPO}
```

If you are using GCS for policy storage, then it will attempt to sync the policies from GCS to the server VM. However if that dir does not exist on GCS, then it will [gracefully fail](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl#L124) and the CV service will not start.

You could also deploy the policies within Terraform, which is done in [one of the test fixtures](https://github.com/forseti-security/terraform-google-forseti/blob/master/test/fixtures/install_simple/main.tf#L178). But I understand if another team is going to be responsible for that. If it is done at a later time, then everything should start working once the policies are copied to GCS. Each time the cron job runs, it will attempt to sync the policies from GCS and restart the CV service.

**Comment by xingao267** [comment]
I just verified that so config-validator service will [try to start](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl#L150) no matter whether `config_validator_enabled` is set to `true` or `false` . We can probably improve that, but it is fine. The service will fail to start. However, the cron job will redownload the policy and [restart](https://github.com/forseti-security/forseti-security/blob/b5ff3f2f8d1cfb13930ba79126fec1909e8b642d/install/gcp/scripts/run_forseti.sh#L38) the `config-validator` service. So from a Forseti functioning perspective, it will still be working.

**Comment by choonchernlim** [comment]
I'm going to close this until I hear back from the security team again. Thanks.
