### ISSUE TITLE
Upgrade automated tests to use Terraform 0.12.20

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#557]
## Story
With the v6.0.0 module release, the Forseti module will be tested against TF 0.12.20 and the team will not support using the module with versions < 0.12.20.

## Solution
Update the tests to use TF 0.12.20, which is tag version `0.7.5` of the dev tools image. Update any documentation.

**Comment by red2k18** [comment]
Do we want to lock down Terraform version 0.12.20?

**Comment by red2k18** [comment]
Locking down to TF version 0.12.20 gives the below error on my local. So, might want to upgrade the dev tools version without locking down the version to 0.12.20. 

![image.png](https://images.zenhubusercontent.com/5d02d4eb534f7a09c8e7f0ae/90d9a3d6-49e8-4cb9-860b-09c96ead88e7)
