### ISSUE TITLE
Builds on master branch are failing due to forseti.rb control

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/terraform-google-forseti#570]
## Story
Builds are currently failing due to these errors:
```
forseti: Forseti GCP resources (1 failed)
×  Control Source Code Error /workspace/test/integration/install_simple/controls/forseti.rb:27 
```

```
×  forseti-nat: Forseti GCP NAT resources (1 failed)
     ×  RouterNat router-ci-forseti-serv-oxkp should exist
     expected RouterNat router-ci-forseti-serv-oxkp to exist
```

[Sample build log](https://pantheon.corp.google.com/cloud-build/builds/02783b4f-7f27-4022-b698-b6b271994b88;step=3?project=cloud-foundation-cicd).

**Comment by red2k18** [comment]
Discussed findings in Story Time meet. In short, it seems to me that there is an issue on the backend.
