### ISSUE TITLE
Update README to reference helpers, not scripts folder for the cleanup script

### ISSUE THREAD

**Issue by annademidova** [forseti-security/terraform-google-forseti#578]
Cleanup instructions reference `scripts` folder which doesn't exist. Please switch to use `helpers` folder and, ideally, keep the commands consistent with the setup script:

`. ./helpers/cleanup.sh -p PROJECT_ID -o ORG_ID -s cloud-foundation-forseti-<suffix>` 

and several lines below:

`. ./helpers/cleanup.sh -p PROJECT_ID -o ORG_ID -s cloud-foundation-forseti-<suffix> -e`

Cheers!

**Comment by hshin-g** [comment]
This has already been addressed in the README- closing.
