### ISSUE TITLE
googleapi: Error 400: Master version "1.14.10-gke.17" is unsupported

### ISSUE THREAD

**Issue by ucantravel** [forseti-security/terraform-google-forseti#579]
I'm trying to deploy using the provided terraform scripts, but I get this error:
There is no specific version specified in the code, so I am not sure how it gets to use this version.

Error: googleapi: Error 400: Master version "1.14.10-gke.17" is unsupported., badRequest

  on .terraform/modules/forseti-on-gke.gke/terraform-google-kubernetes-engine-7.2.0/modules/beta-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
  22: resource "google_container_cluster" "primary" {

**Comment by gkowalski-google** [comment]
Hi @ucantravel, sorry for that issue. That version was the default version when the last release went out. If you are following the on-gke-end-to-end example, you can try using a different version [here](https://github.com/forseti-security/terraform-google-forseti/blob/master/examples/on_gke_end_to_end/variables.tf#L137). I recently updated my cluster to use version `1.15.11-gke.9` and that worked.

**Comment by ucantravel** [comment]
Much appreciated pointing me in the right direction!
