### ISSUE TITLE
forseti install on tiller v2.16.8 failed with provider 0.10.5

### ISSUE THREAD

**Issue by Jean-Mercier** [forseti-security/terraform-google-forseti#590]
Hello 

Install with provider helm 0.10.5 failed
We needed to downgrade provider version to 0.10.3, after that we have a working execution of the terraform apply

this is the error : 
```
module.forseti-on-gke.module.forseti.helm_release.forseti-security: Creating...
Error: rpc error: code = Unknown desc = render error in "forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml": template: forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml:15:6: executing "forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml" at <(.Values.networkPolicy.enabled) and (.Values.orchestrator.enabled)>: can't give argument to non-function .Values.networkPolicy.enabled
  on .terraform/modules/forseti-on-gke/terraform-google-forseti-5.2.1/modules/on_gke/main.tf line 221, in resource "helm_release" "forseti-security":
 221: resource "helm_release" "forseti-security" {
```

i think it's due to this issue on helm who break working chart : 
https://github.com/helm/helm/issues/8311

Thanks

**Comment by gkowalski-google** [comment]
Hi @Jean-Mercier, thanks for submitting this issue. In the past I had been using 0.10.4 which should work. It is strange to see a micro version introduce a breaking change. We will try to get this working with 0.10.5 for the next release.

**Comment by paul-r0ss** [comment]
Hi, we are experiencing the same issue. Downgrading to 0.10.4 did not help.

**Comment by Pavloro** [comment]
the issue still remains

**Comment by e-koma** [comment]
the issue still remains. I also encountered.

**Comment by El-Dringo-Brannde** [comment]
I too have this issue, and can't deploy.

**Comment by robhyb19** [comment]
Seeing this same issue as well. Running on helm provider 0.10.4
