### ISSUE TITLE
Forseti on GKE uses default node pool name

### ISSUE THREAD

**Issue by paul-r0ss** [forseti-security/terraform-google-forseti#612]
When we are trying to deploy Forseti with terraform on existing GKE cluster, we are experiencing that the module uses a default value for `nodeSelctors`. It leads to time out under deploy with helm.
Pod cannot start and fails with:
`pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't match node selector`

**Actual Behaviour**
[terraform config](https://gist.github.com/paul-r0ss/268dff329130731e3030c30a7a9dee81)

[output](https://gist.github.com/paul-r0ss/aa27eaca1787e33245a402a802b94477) from `terraform plan`

**Expected Behaviour**
output from `terraform plan`

` ...`
`          + "nodeSelectors: ['cloud.google.com/gke-nodepool=pool-1']",`

**Other info**
We need to use helm chart 0.10.4 due to an error we get with 0.10.5 ([related this issue](https://github.com/forseti-security/terraform-google-forseti/issues/590):

> module.forseti-on-gke.module.forseti.data.http.server_config_contents: Refreshing state...
> module.forseti-on-gke.module.forseti.helm_release.forseti-security: Creating...
> Error: rpc error: code = Unknown desc = render error in "forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml": template: forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml:15:6: executing "forseti-security/templates/orchestrator/network-policies/default-deny-ingress-egress.yaml" at <(.Values.networkPolicy.enabled) and (.Values.orchestrator.enabled)>: can't give argument to non-function .Values.networkPolicy.enabled
>   on .terraform/modules/forseti-on-gke/modules/on_gke/main.tf line 221, in resource "helm_release" "forseti-security":
>  221: resource "helm_release" "forseti-security"

**Comment by Pavloro** [comment]
the problem is still not resolved

**Comment by Pavloro** [comment]
Hi, It's not possible to override default value in NodeSelectors in forseti chart.
