### ISSUE TITLE
Server/client startup script failing

### ISSUE THREAD

**Issue by soumyadipDe** [forseti-security/terraform-google-forseti#621]
Hi,
Currently while running the terraform script the startup script in client/server fails saying,
`No apt package "google-cloud-sdk"`

Is it something wrong at my end or something changed recently?

Thanks

**Comment by ebalduf** [comment]
The version called out for default (289) is no longer available.  Add the following line to your main.tf and it should make it startup.  

google_cloud_sdk_version = "335.0.0-0"

**Comment by e-koma** [comment]
I created a pull request for this.
#622
