### ISSUE TITLE
Remove `credentials_path` from examples and fixtures

### ISSUE THREAD

**Issue by morgante** [forseti-security/terraform-google-forseti#7]
Currently, the module requires passing a path to a Service Account key as an argument. This can make it harder to run as part of a pipeline where (a) an environment variable is used to track the file location (b) the application default credentials on a GCE VM should be used.

**Comment by morgante** [comment]
Regarding scenario (a), if you are exporting the credential path to an environment variable as part of a CI pipeline this is possible to do with the module today. As follows:

1. Declare a variable for your credentials path and use it in the module config:

```
variable "credentials_file_path" {
  description = "Path to service account json"
}

module "forseti-install-simple" {
  source                       = "../../"
  gsuite_admin_email           = "${var.gsuite_admin_email}"
  project_id                   = "${var.project_id}"
  sendgrid_api_key             = "${var.sendgrid_api_key}"
  notification_recipient_email = "${var.notification_recipient_email}"
  credentials_file_path        = "${var.credentials_file_path}"
}
```

2. Then, this variable can be populated using an [environment variable](https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name).

```
export TF_VAR_credentials_file_path=/my/path/credentials.json
```

**Comment by adrienthebo** [comment]
The Forseti v1.0 rewrite appears to have dropped the requirements for a `credentials_file_path` variable in f34744fa336e08836064b14073858773606a795c. We still reference the `credentials_path` in the examples; we should drop that configuration in favor of Application Default Credentials.

**Comment by gkowalski-google** [comment]
The only example still using this is the external_ip example. Remove from this example.
