### ISSUE TITLE
Allow VM restart to pick up patches

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/terraform-google-forseti#95]
e.g. v.2.13.0 -> v2.13.1

patches are mainly for bug fixes so auto pickup would be more user friendly

**Comment by morgante** [comment]
I'm not convinced that this sort of auto-patching functionality is a good idea. For one thing, it violates a basic idea of immutable infrastructure.

Instead we should simply release a new patch version of the module.

Note that Terraform allows flexible [version constraints](https://www.terraform.io/docs/configuration/modules.html#module-versions) so users *can* declare they want the latest patch version. (Ex. `~> 2.13.0`).

**Comment by kevensen** [comment]
I agree with @morgante.  While automated patching can be convenient, patching of critical infrastructure should be deliberate.

@joecheuk Does this issue merit further discussion?

**Comment by gkowalski-google** [comment]
@kevensen @joecheuk Any more thought on this issue? I agree that we should not auto-patch on server restart and allow users to control the release from Terraform configuration. Can we close this?

**Comment by kevensen** [comment]
@gkowalski-google I have no further thoughts.  Please close at your discretion.

**Comment by dekuhn** [comment]
There is consensus we should not support this. Closing this issue.
